charts/juror-bureau/Chart.yaml
charts/juror-bureau/values.dev.template.yaml
charts/juror-bureau/values.yaml

update api endpoint

---

charts/juror-bureau/values.stg.template.yaml

reintroduce stg environment

---

client/templates/summons-management/_common/details-banner-new.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-6577
Updating code to bring reply method value out of the response object to render correctly
```
[ ] Yes
[x ] No
```

hotfix/JM-6577 Digital response is actually paper in the DB

---

client/templates/summons-management/_common/details-banner-new.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-6577
Updated to allow method in URL as well as replyMethod in DTO to be interpreted
the first url has method in URL
http://0.0.0.0:3000/summons-replies/response/041500058/paper
the second url has replyMethod in DTO
http://0.0.0.0:3000/response/041500058
```
[ ] Yes
[ x] No
```

hotfix/JM-6577 updated to allow method and replyMethod

---

client/templates/includes/scripts.njk
server/objects/deferral-mod.js
server/objects/deferral-mod.spec.js
server/objects/summons-management.spec.js

[JM-6594](https://centralgovernmentcgi.atlassian.net/browse/JM-6594)
- Fix a couple of failing tests
- Add missing gds script
```
[ ] Yes
[x] No
```

fix frontend failing tests and add missing js script

---

client/templates/search/index.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-6578
Updated template to render the date as expected
```
[ ] Yes
[ x] No
```

hotfix/JM-6578 Fix date on response search results

---

server/lib/mod-utils.js

[JM-6314](https://centralgovernmentcgi.atlassian.net/browse/JM-6314) 
Update to align Postponed letter type with BE
BE change made on this PR [https://github.com/hmcts/juror-api/pull/92/](https://github.com/hmcts/juror-api/pull/92/)
```
[ ] Yes
[x] No
```

hotfix/JM-6314 - Update to align the postponed letter type with BE

---

client/templates/administration/_common/court-administration-nav.njk
client/templates/administration/room-locations/add-edit-room.njk
client/templates/administration/room-locations/rooms.njk
server/components/auth/index.js
server/config/validation/create-courtroom.js
server/config/validation/create-courtroom.spec.js
server/objects/administration.js
server/routes/administration/index.js
server/routes/administration/room-locations/index.js
server/routes/administration/room-locations/room-locations.controller.js

[JM-6254](https://centralgovernmentcgi.atlassian.net/browse/JM-6254)
Added functionality for Court Manager's to view, add, and edit court room locations at their court.
```
[ ] Yes
[x] No
```

feature/JM-6254: Manage court room locations

---

server/routes/administration/room-locations/room-locations.controller.js

Updated some broken routing
```
[ ] Yes
[x] No
```

updated url routing

---

server/config/validation/add-smartcard-spend.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6589
Added smart card spend upper limit
```
[ ] Yes
[X] No
```

Added Smart Card spend upper limit

---

server/routes/juror-management/postpone/postpone.controller.js
server/routes/juror-management/reassign/reassign.controller.js
server/routes/juror-management/update/juror-update.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/summons-management/process-reply/process-reply.controller.js

[JM-5893](https://centralgovernmentcgi.atlassian.net/browse/JM-5893)
Enabled 'Postpone' and 'Reassign' options when processing a late summons reply.
(to test this: process a summons reply where the service start date is in the past)
```
[ ] Yes
[x] No
```

hotfix/JM-5893 - Reassign and Postpone individual flow as court user erroring

---

server/objects/pool-management.js
server/objects/pool-management.spec.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js

[JM-5919](https://centralgovernmentcgi.atlassian.net/browse/JM-5919)
Added new API endpoint which returns Court-owned only pools. 
```
[ ] Yes
[x] No
```

hotfix/JM-5919 - Getting error page while creating  a Juror record

---

server/lib/mod-utils.js

N/A
I need debug logs
```
[ ] Yes
[x] No
```

add debug logs

---

client/templates/juror-management/juror-record/summons.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-5074
Update to show the summons reply link only if there is a valid reply record (by checking a reply date)
```
[ ] Yes
[ x] No
```

hotfix/JM-5704 App crashes when clicking View Summons

---

client/js/components/search.js
client/templates/search/index.njk
server/components/auth/user-type.js
server/routes/search/search.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6698
https://centralgovernmentcgi.atlassian.net/browse/JM-6702
- fix search results missing what the search is for and wrong labels
- fix another bug related to the search results not rendering properly
```
[ ] Yes
[x] No
```

hotfix/JM-6690 & JM-6702

---

Dockerfile
package.json
server/config/express.js
server/lib/session-config.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6721
- Improve secure cookies
- Add docker changes to run the new prod script
- Add a prod script to package.json
```
[ ] Yes
[ ] No
[x] Maybe
```

Secure cookies

---

server/objects/juror-record.js
server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6734
- Fix urljoin call for when trying to add contact logs through a juror record
- Also fix another bug
```
[ ] Yes
[x] No
```

fix url builder for adding contact logs

---

server/routes/juror-management/reassign/reassign.controller.js

[JM-6716](https://centralgovernmentcgi.atlassian.net/browse/JM-6716)
Fixed an invalid assignment to a const.
```
[ ] Yes
[x] No
```

hotfix/JM-6716 - Invalid assignment to const

---

client/templates/reporting/standard-reports/pool-search.njk
client/templates/reporting/standard-reports/standard-report.njk
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6694
- Add print functionality to print next attendance date pdfs
```
[ ] Yes
[x] No
```

JM-6694: Print a next attendance date report

---

server/objects/expenses.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6786
Fix issue with function being undefined
```
[ ] Yes
[x] No
```

fix undefined function on default expenses

---

client/templates/reporting/index.njk
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6400
Added undelivered list report
```
[ ] Yes
[x] No
```

feature/JM-6400: Undelivered List Report

---

client/templates/response/_partials/update-header.njk
client/templates/response/detail.njk

[JM-6670 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6670)
- Changed 'Super urgent' tag to 'Urgent'
- 'Process reply' button now only available the matching owner values.
- Removed rawProcessingStatus value from njk files as it is no longer available (checked with BE devs).
```
[ ] Yes
[x] No
```

hotfix/JM-6670 - Shouldn't be able to process a super urgent response

---

server/lib/mod-utils.js
server/routes/documents/helper/table-generator.js
server/routes/documents/letters-list/letters-list.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6259
Added handling for bureau users to print the summons reminder letter.
Needed to add clauses for letters that have never been printed to the table generator.
And added handling for posting these fresh print requests to the API.
```
[ ] Yes
[x] No
```

feature/JM-6259: Send/Resend Summons reminder letter

---

server/routes/juror-management/juror-record/juror-record.controller.js

remove debugger kw

---

server/routes/juror-management/juror-record/index.js

N/A
fix a bug with changing the next due at court date
```
[ ] Yes
[x] No
```

fix change next due at court date

---

server/lib/session-config.js

N/A
Add same-site strict to cookies.
```
[ ] Yes
[x] No
```

add samesite strict config to cookies

---

server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6814
Bulk change date for a single juror was interpreting the juror number string as an array and failing. This change enforces being an array.
```
[ ] Yes
[ ] No
```

Bug (JM-6814) fix sending juror numbers as string instead of array

---

server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js

n/a
fix a payload sending a wrong property
```
[ ] Yes
[x] No
```

fix confirm attendance day

---

server/config/validation/paper-reply.js

N/A
fix frontend phone number regex for paper-reply
```
[ ] Yes
[x] No
```

fix phone number regex

---

client/templates/pool-management/pool-overview/court-pool-overview.njk
server/routes/pool-management/request-pool/request-pool.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6779
Fixes the display of nil pools for courts. Also fixes the flow for bureau users creating a nil pool.
```
[ ] Yes
[x] No
```

Bug (JM-6779) fix nil pool display message and court nil pool flow

---

server/lib/mod-utils.js
server/routes/trial-management/generate-panel/generate-panel.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6875
Replaces a generic error message with the error from the API.
```
[ ] Yes
[X] No
```

Bug (JM-6875) replace generic error with specific error banner

---

client/templates/juror-management/juror-record/overview.njk
server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6757
- improve the police_check statuses display
```
[ ] Yes
[x] No
```

hotfix/JM-6757: Police check statuses

---

client/templates/juror-management/juror-record/confirm-identity.njk
client/templates/juror-management/juror-record/overview.njk
server/config/validation/confirm-identity.js
server/objects/administration.js
server/objects/confirm-identity.js
server/objects/index.js
server/routes/juror-management/juror-record/confirm-identity/confirm-identity.controller.js
server/routes/juror-management/juror-record/confirm-identity/index.js
server/routes/juror-management/juror-record/index.js
server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6598
- implement the id-check journey
- refactor the juror-record overview tab to use both the overview and details endpoint for both check id and police checks
- add new DAO to submit the identity check data
```
[ ] Yes
[x] No
```

feature/JM-6598: juror identity check

---

server/routes/juror-management/juror-record/juror-record.controller.js

fixed resolve police check in juror record overview
```
[ ] Yes
[x] No
```

hotfix/juror-record-overview-response: fixed resolve police check in juror record overview

---

server/routes/dashboard/dashboard.controller.js

JDB-5557 - Dashboard FE - Chart label/tooltip rendering

---

server/routes/pool-management/pool-overview/pool-overview.controller.js

N/A
- use pool location code to set the juror-record location code from the pool overview table
```
[ ] Yes
[ ] No
```

use pool location code

---

server/config/validation/create-trial.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6870
Added missing validation check
```
[ ] Yes
[x ] No
```

jm-6870: If defendant name longer than 16 chars on create trial, it fails

---

client/templates/juror-management/expense-record/expense-record.njk
client/templates/juror-management/juror-record/attendance.njk
server/objects/juror-record.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6935
https://centralgovernmentcgi.atlassian.net/browse/JM-6936
Hide 'add non-attendance day' from FE, except if the juror is responded, panelled or juror.
NB: would be good to disable on BE as well.
```
[ ] Yes
[X] No
```

Bug (JM-6935, JM-6936) hide 'add non-attendance day' except in good statuses

---

server/config/validation/record-create-manual.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6733
Enforcing space in create juror record postcode to ensure that API can recognise the postcode to check catchment
```
[ ] Yes
[x] No
```

hotfix/JM-6733: Error on create juror record postcode

---

client/templates/pool-management/pool-overview/pool-history.njk
server/routes/pool-management/pool-overview/pool-overview.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6960
https://centralgovernmentcgi.atlassian.net/browse/JM-6962
- fix sorting on pool overview
- fix errors not being caught
```
[ ] Yes
[x] No
```

hotfix/JM-6960 & hotfix/JM-6962

---

client/templates/juror-management/juror-record/attendance.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-6936
Block attendance days being added for jurors who aren't in appropriate states.
```
[ ] Yes
[X] No
```

Bug (JM-6936) block adding attendance days for bad juror states

---

client/templates/pool-management/_common/check-request-details.njk
server/lib/mod-utils.js
server/routes/pool-management/request-pool/request-pool.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-4673
Stops the FE from requesting more deferred jurors than required jurors, to stop negative number of jurors being summoned
```
[ ] Yes
[X] No
```

Bug (JM-4673) block negative number of jurors from being summoned

---

server/routes/documents/print.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6583
Fixes printing a pdf with no expenses throwing an exception
```
[ ] Yes
[X] No
```

Bug (JM-6583) Fix certificate of attendance crashing with no expenses

---

client/templates/juror-management/reassign/pools.njk
server/config/validation/pool-management.js
server/routes/juror-management/reassign/reassign.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6778
Implemented updated API to create a new pool when reassigning
```
[ ] Yes
[x] No
```

hotfix/JM-6778: Court User - Reassign 'Create new pool' option

---

server/routes/pool-management/pool-overview/pool-overview.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6933
Updated rendering of court pool history to use the correct file.
```
[ ] Yes
[x] No
```

hotfix/JM-6933: Fixed rendering for court pool history

---

server/objects/responses.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6984)
Updated middleware to point to new (optimised) get response counts API 
```
[ ] Yes
[X] No
```

Code Optimisations for your work page

---

server/objects/responses.js

n/a
revert jm-6984 changes
```
[ ] Yes
[x] No
```

revert jm-6984 changes

---

server/config/validation/edit-judge.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6944
Added validation for judge code and name to accept the correct number of characters
```
[ ] Yes
[x] No
```

hotfix/jm-6944- Entering a Judge code that is longer then 4 character causes issues

---

server/routes/pool-management/pool-management.controller.js

Make at court tab priority for court users

---

client/templates/custom-components/super-navigation/super-navigation.njk
server/routes/trial-management/add-panel-members/index.js
server/routes/trial-management/create-trial/index.js
server/routes/trial-management/edit-trial/index.js
server/routes/trial-management/empanel-jury/index.js
server/routes/trial-management/generate-panel/index.js
server/routes/trial-management/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6963
Added court auth to trial management routes
```
[ ] Yes
[x] No
```

hotfix/JM-6963: Added court auth to trial management routes

---

client/templates/juror-management/_common/juror-management-nav.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-7018
Fix rights for Juror Management Nav Bar.
```
[ ] Yes
[x] No
```

hotfix/JM-7018: Fix rights for juror management nav

---

client/templates/documents/status-changed.njk
server/routes/documents/index.js
server/routes/documents/letters-list/letters-list.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6227
- handle printing letters for jurors that got their statuses updated
```
[ ] Yes
[x] No
```

hotfix/JM-6227: Display list with jurors who had statuses changed when sending to print

---

server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7023
Allow user to access expenses tab if there is no attendances recorded for them.
```
[ ] Yes
[x] No
```

hotifx/JM-7023: Fixed issue for expenses tab if juror has no attendances

---

server/routes/pool-management/pool-management.controller.js

N/A
- fix tab not setting properly
```
[ ] Yes
[x] No
```

fix tab not setting properly

---

server/config/validation/bank-details.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6587
Add error for empty bank details.
Reinstate errors for individual fields only if there is data in another field.
```
[ ] Yes
[x] No
```

hotfix/JM-6587: Add error for empty bank details

---

README.md

force build

---

client/templates/administration/system-codes.njk

n/a
- we changed a comma for a period and broke something 😄 
```
[ ] Yes
[x] No
```

fix the system-codes views

---

client/templates/trial-management/returns/confirm-return.njk
server/config/validation/return-panel-jury.js
server/routes/trial-management/returns.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7022
Added check in field to return jurors without confirming.
```
[ ] Yes
[x] No
```

hotfix/JM-7022: Added check in field to return jurors without confirming

---

client/templates/administration/_common/court-administration-nav.njk
client/templates/administration/court-details.njk
client/templates/administration/expense-limits-court.njk
client/templates/custom-components/super-navigation/super-navigation.njk
server/routes/administration/court-details/index.js
server/routes/administration/expense-limits-court/index.js
server/routes/administration/judges/index.js
server/routes/administration/non-sitting-days/non-sitting-days.controller.js
server/routes/administration/room-locations/index.js

[JM-7093 - Can't see admin page as a normal officer 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7093)
- Given access to Standard court users to view Court Administration page
- Removed access to Administration Users page for Standard court users
- Limited Standard court users to only view Expense limits and not edit
```
[ ] Yes
[x] No
```

hotfix/JM-7093 - Can't see admin page as a normal officer

---

client/js/expenses-summary.js
client/templates/expenses/_partials/travel.njk
server/config/validation/enter-expenses.js
server/config/validation/enter-expenses.spec.js
server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js

[JM-7061 - Define the number of motorcycle passengers 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7061)
- Added number of passengers by motorcycle conditional input (daily expenses).
```
[ ] Yes
[x] No
```

hotfix/JM-7061 - Define the number of motorcycle passengers

---

client/scss/mod-custom.scss
client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6470
Implemented the current pool status report for bureau and court users.
Updated report headings in reportKeys to be an object with lists for left and right (some reports have more detail on left or right column).
Updated handling for list objects in table (if not an address, show the key and value)
```
[ ] Yes
[x] No
```

feature/JM-6470: Current pool status report

---

server/routes/allocation/allocation.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7127)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-bureau&pullRequest=282)
the numbers on the assign replies screen and the amount a officer actually has is different
```
[ ] Yes
[X] No
```

UAT - Numbers on assign reply screen and actual amount on officer to do is different

---

client/templates/trial-management/trial-detail.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6394
Updated menu buttons on trial detail screen - added print button menu.
Added the trail panel summary report - accessed from trial detail screen
```
[ ] Yes
[x] No
```

Feature/JM-6394: Panel Summary Report

---

server/routes/documents/print.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7112)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-bureau&pullRequest=294)
!Screenshot 2024-04-22 at 12.00.42.png|width=728,height=847,alt="Screenshot 2024-04-22 at 12.00.42.png"!
```
[ ] Yes
[X] No
```

Attendance letter says non-attendance even on attendance days

---

server/components/auth/index.js
server/routes/reporting/standard-report/standard-report.controller.js

fix loc code for reports

---

server/config/validation/change-attendance-date.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js

[JM-6795 - Error message required when setting next due at court date 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6795)
- Added check for jurors with summoned status when setting next due at court date.
```
[ ] Yes
[x] No
```

hotfix/JM-6795 - Error message required when setting next due at court date

---

server/config/validation/report-search-by.js
server/routes/reporting/postponed-report/postponed.controller.js

Updating standardised report search validation to make it easier to reuse.
```
[ ] Yes
[x] No
```

Chore: Update standard report search validation

---

server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7172
If no date is provided for report content display '-' rather than todays date
```
[ ] Yes
[x] No
```

hotfix/JM-7172: Update LocalDate handling for null report dates

---

server/routes/search/search.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7162)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=%pullRequestNumber%)
- update the way the juror record search works
```
[ ] Yes
[X] No
```

FE Implementation

---

server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7179
Reports were breaking if no data returned for certain data types, replaced with hyphen if nothing returned.
```
[ ] Yes
[x] No
```

hotfix/JM-7179: Show hyphen if no data in reports

---

client/templates/response/_partials/call-logs.njk
client/templates/response/_partials/notes.njk
client/templates/response/log.njk
server/routes/juror-management/juror-record/index.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/summons-management/index.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7128)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=310)
cant add notes or logs from the summons reply:
!image-20240423-195653.png|width=451,height=150,alt="image-20240423-195653.png"!
```
[ ] Yes
[X] No
```

UAT - Notes and logs not working from summons reply

---

client/templates/juror-management/create-record-manual/juror-contact.njk
client/templates/juror-management/create-record-manual/notes.njk
server/config/validation/record-create-manual.js
server/lib/mod-utils.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7164)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=317)
Validation checks required for phone number details
!Screenshot 2024-04-29 at 13.33.15.png|width=1408,height=481,alt="Screenshot 2024-04-29 at 13.33.15.png"!
```
[ ] Yes
[X] No
```

Unable to manually create a juror

---

server/routes/juror-management/edit/juror-edit.controller.js
server/routes/summons-management/paper-reply/paper-reply.controller.js
server/routes/summons-management/update/juror-details.controller.js

[JM-6350 - If you correct an error in name and change name on the same screen, the changed name is not saved 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6350)
- Added asynchronous call for fixNameObj to avoid clashing when entering a new name.
```
[ ] Yes
[x] No
```

hotfix/JM-6350 - Error when fixing current name and entering a new name

---

server/routes/administration/users/users.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7187)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=319)
Insert a last login date/time in the database for existing user(s)
Log in as a system admin user
Navigate to the Users screen
Verify the last login date is displayed correctly:
!image-20240501-091504.png|width=1422,height=740,alt="image-20240501-091504.png"!
```
[ ] Yes
[X] No
```

Last Login Date incorrectly displayed on System Admin > Users screen

---

client/scss/mod-custom.scss
client/templates/reporting/standard-reports/court-select.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7188
Added an initial version of the court select screen, as needed in several of the reporting journeys.
```
[ ] Yes
[x] No
```

task/JM-7188: Standardised Reports Court Select Screen

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/standard-reports/date-search.njk
server/config/validation/report-search-by.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-5911
Added handling for Bulk Print Audit Report.
Added standardised date search screen.
```
[ ] Yes
[x] No
```

Feature/JM-5911: Bulk-Print Audit Report (Abaccus Report)

---

client/templates/response/_partials/reasonable-adjustments.njk

JM-7215 - Reasonable adjustments display for digital repsonse

---

client/templates/trial-management/trial-detail.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6396
Added Trial Detail Report.
```
[ ] Yes
[x] No
```

feature/JM-6396: Trial Detail Report

---

client/templates/trial-management/trial-detail.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6402
Added Jury List report.
```
[ ] Yes
[x] No
```

feature/JM-6402: Jury List Report

---

server/routes/juror-management/update/juror-update.responded.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7151
Add validation rule to front end to handle 422 error code
```
[ ] Yes
[x ] No
```

JM-7151: It is possible to mark a juror as responded without a DOB

---

client/templates/reporting/standard-reports/standard-report.njk
client/templates/shared/complete-service/complete-service-confirm.njk
server/routes/reporting/incomplete-service/incomplete-service.controller.js
server/routes/reporting/incomplete-service/index.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/shared/complete-service/complete-service.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6379
Updated INcomplete service report layout.
Updated complete service flow to handle completing from the reports screen.
```
[ ] Yes
[x] No
```

feature/JM-6379: Incomplete Service Report

---

client/templates/pool-management/pool-overview/bureau-pool-overview.njk

[JM-7047 - Unable to edit and increase number of jurors in a pool request 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7047)
- Made 'Edit pool' button available on pool requests for Bureau users.
BE PR: https://github.com/hmcts/juror-api/pull/307
```
[ ] Yes
[x] No
```

hotfix/JM-7047 - Edit pool on pool requests for Bureau users

---

server/routes/administration/users/assign-courts/assign-courts.js

[JM-7200 - As a system admin, users can search for satellite court loc codes when assigning courts to users 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7200)
- Filtered out satellites from user filtered list.
```
[ ] Yes
[x] No
```

hotfix/JM-7200 - satellite courts appearing when assigning courts to users (Admin user)

---

server/config/validation/deferral-mod.js
server/routes/juror-management/update/juror-update.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7251)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=341)
When updating jurors record to accept/reject a referral request it will fail with the error {{“Date cannot be earlier than orginal summons"}} - Even when the date is not earlier than original summons
```
[ ] Yes
[X] No
```

Granting or refusing deferral requests as a Bureau user is failing

---

client/js/pool-overview.js
client/templates/pool-management/pool-overview/_partials/filters.njk
client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
client/templates/pool-management/pool-overview/court-pool-jurors.njk
server/lib/mod-utils.js
server/objects/index.js
server/objects/pool-members.js
server/routes/pool-management/pool-overview/bureau-view.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
server/routes/pool-management/pool-overview/paginate-jurors-list.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6931
Fixed functionality for top filter
Changed default to responded on both bureau and court
This change impacts both types of user
```
[ ] Yes
[ x] No
```

Bug/JM-6931 - Pool overview (as a bureau officer) nothing happens when I click All Jurors

---

client/templates/response/_partials/juror-details.njk
client/templates/response/detail.njk

n/a
- the details container was missing a closing tag that broke the page structure
```
[ ] Yes
[x] No
```

fix the summons details page

---

client/templates/administration/judges/judges.njk
client/templates/administration/users/assign-courts/_partials/assign-courts-table.njk
client/templates/administration/users/assign-courts/assign-courts.njk
client/templates/administration/users/court-bureau-users.njk
client/templates/administration/users/users.njk
client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
client/templates/juror-management/approve-expenses/approve-expenses.njk
client/templates/juror-management/manage-jurors/approve-jurors.njk
client/templates/juror-management/reassign/pools.njk
client/templates/pool-management/deferral-maintenance/_partials/pools-table.njk
client/templates/reporting/some-report/index.njk
client/templates/reporting/standard-reports/court-select.njk
client/templates/trial-management/_partials/trial-panel.njk
client/templates/trial-management/trials.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7276)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=345)
```
[ ] Yes
[X] No
```

As a FE dev I want to update inline js events to be set on script tags for security enforcement

---

client/templates/response/_partials/reasonable-adjustments.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7241)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=347)
Should be more sensitively referred to
!image-20240508-110002.png|width=706,height=593,alt="image-20240508-110002.png"!
```
[ ] Yes
[X] No
```

ID on reasonable adjustments is "disability"

---

server/lib/reports/financial-audit.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7283
Adds audit number to footer of audit reports
```
[ ] Yes
[X] No
```

Bug (JM-7283) add audit number to footer

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
client/templates/reporting/standard-reports/date-search.njk
client/templates/reporting/standard-reports/date-search/fixed-range.njk
client/templates/reporting/standard-reports/date-search/from-to.njk
server/config/validation/report-search-by.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6377)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=350)
*Acceptance Criteria*
·       Continue (Tab)
·       Cancel (Hyperlink)
 
#* Juror number
#* First name
#* Last name
#* Pool number
#* Phone
#* Appearance date
#* Reasonable adjustments
#* Court name
List of jurors in that pool
```
[ ] Yes
[X] No
```

As a jury/bureau officer I wan to generate a special needs (Reasonable adjustment) report (FE)

---

server/routes/reporting/standard-report/standard-report.controller.js

n/a
- make the pool number in reports be a clickable link to go to pools
```
[ ] Yes
[x] No
```

make the pool number in reports be a clickable link

---

server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

[JM-7270 - Bulk postponing a pool with causes unhandled error screen 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7270)
- Fixed selectedJurors object when 'check-all' has been selected.
```
[ ] Yes
[x] No
```

hotfix/JM-7270 - Bulk postponing a pool with causes unhandled error screen

---

server/objects/responses.js
server/routes/completed/completed.controller.js
server/routes/completed/index.js
server/routes/inbox/inbox.controller.js
server/routes/inbox/index.js
server/routes/pending/index.js
server/routes/pending/pending.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7311)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=365)
The “You Work” pages (todo, awaiting-info, complete) are failing PVT as page load times takes longer then 1.5 seconds 95% of the time.
!image-20240516-165215.png|width=1313,height=465,alt="image-20240516-165215.png"!
```
[ ] Yes
[X] No
```

Improve the performance of the "Your Work" pages

---

server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6480
Added 31 day date range validation for daily utilisation report.
```
[ ] Yes
[x] No
```

hotfix/Jm-6480: Add date range length validation to daily utilisation

---

client/js/document-letters.js
client/templates/documents/_common/letters-list.njk
server/routes/documents/helper/table-generator.js
server/routes/documents/letters-list/letters-list.controller.js

[JM-7249 UAT - No select all button at the top of letters for Bureau 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7249)
- Added check all checkbox for Bureau users only
- Added logic and Ajax calls for checking/unchecking all
```
[ ] Yes
[x] No
```

hotfix/JM-7249 - UAT - No select all button at the top of letters for Bureau

---

client/templates/reporting/daily-utilisation/uncompleted-jurors.njk
client/templates/reporting/incomplete-service/cutoff-date.njk
client/templates/reporting/persons-attending/attendance-date.njk
client/templates/reporting/standard-reports/court-select.njk
client/templates/reporting/standard-reports/date-search.njk
client/templates/reporting/standard-reports/pool-search.njk
client/templates/reporting/standard-reports/standard-report.njk
server/lib/mod-utils.js
server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js
server/routes/reporting/daily-utilisation/daily-utilisation.controller.js

N/A
- update page titles for reports
```
[ ] Yes
[x] No
```

update page titles on reports pages

---

server/routes/juror-management/update/juror-update.controller.js

N/A
- update juror-update post to fetch systemcodes if they're not set previously
```
[ ] Yes
[x] No
```

undefined deferral reasons on juror update

---

server/routes/reporting/standard-report/definitions.js

Fixed issue with utilisation report first time render
```
[ ] Yes
[X] No
```

Fixed issue with utilisation report first time render

---

client/scss/mod-custom.scss
client/templates/reporting/standard-reports/standard-report.njk
client/templates/trial-management/trial-detail.njk
server/lib/reports/default-layout.js
server/lib/reports/single-generator.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7327)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=380)
*Acceptance criteria*
 
·       Jury list
·       Ballot cards
·       Panel list (summary)
·       Panel list (detailed)
·       Panel members status report
#* Back (Hyperlink)
#* *Panel member status report* (Header)
#* Print (Tab)
#* *Trial number*
#* *Names*
#* *Courtroom*
#* *Judge*
#* *Report created*
#* *Time created*
#* *Court name*
#* Panelled (count)
#* Empanelled (count)
#* Not Used (count)
#* Challenged (not used)
#* Returned jurors (count)
#* Juror number
#* Panel status
```
[ ] Yes
[X] No
```

As a court officer I want to generate a Panel member status report (FE)

---

client/templates/reporting/court-statistics.njk
client/templates/reporting/monthly-utilisation/confirm-prepare.njk
client/templates/reporting/monthly-utilisation/prepare-select-month.njk
client/templates/reporting/monthly-utilisation/view-select-month.njk
client/templates/reporting/standard-reports/standard-report.njk
server/objects/reports.js
server/routes/reporting/bespoke-report/bespoke-report-body.js
server/routes/reporting/bespoke-report/bespoke-report-print.js
server/routes/reporting/monthly-utilisation/index.js
server/routes/reporting/monthly-utilisation/monthly-utilisation.controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/report-export.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6482
https://centralgovernmentcgi.atlassian.net/browse/JM-6484
Added monthly utilisation report
```
[ ] Yes
[x] No
```

feature/JM-6482&6484: Monthly Utilisation Report

---

server/routes/reporting/standard-report/definitions.js

N/A
- update the panel-member-status report definition to correctly sum the values for the large tags
```
[ ] Yes
[x] No
```

fix/JM-7327: panel members status report

---

client/templates/reporting/court-reports.njk
server/config/validation/report-search-by.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6366
Added Absences report.
Removed prefix and link from grouped reports definitions, should now be handled by a transformer function, distinct to each report.
```
[ ] Yes
[x] No
```

feature/JM-6366: Absences Report

---

client/templates/reporting/court-statistics.njk
client/templates/reporting/standard-reports/standard-report.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6410
Added Trial Statistics report.
Updated large totals to allow for variation in sizes.
```
[ ] Yes
[x] No
```

feature/JM-6410: Jury Summary Report (Trial Statistics)

---

client/templates/reporting/available-list/search-by.njk
client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
server/config/validation/report-search-by.js
server/routes/reporting/available-list/available-list.controller.js
server/routes/reporting/available-list/index.js
server/routes/reporting/index.js
server/routes/reporting/persons-attending/persons-attending-controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6414
Added available list reports.
Added queryParams definition to define values of any required query params throughout all report journeys.
```
[ ] Yes
[x] No
```

feature/JM-6414: Available List reports

---

server/lib/mod-utils.js
server/objects/create-trial.js
server/objects/create-trial.spec.js
server/routes/messaging/send-messages.controller.js
server/routes/trial-management/trial-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7437
Updated trials list object to use new endpoint.
```
[ ] Yes
[x] No
```

task/JM-7437: Update to use new trials list endpoint

---

server/routes/reporting/standard-report/definitions.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6414
Updated styling for printing Pool Number with pool type.
```
[ ] Yes
[x] No
```

update pool type print style

---

client/templates/reporting/court-reports.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7323
Added On Call List.
```
[ ] Yes
[x] No
```

feature/JM-7323: On Call List

---

client/scss/mod-custom.scss
client/templates/reporting/court-reports.njk
client/templates/reporting/standard-reports/trial-select.njk
server/lib/mod-utils.js
server/lib/mod-utils.spec.js
server/routes/messaging/send-messages.controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6422
https://centralgovernmentcgi.atlassian.net/browse/JM-6425
Added trial selection screen for reports.
Added Trial Attendance Report.
Added Jury Cost Bill.
```
[ ] Yes
[x] No
```

Feature/JM-6422&6425: Trial Attendance Report & Jury Cost Bill

---

client/templates/reporting/court-reports.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7319
Added Payment Status Report.
```
[ ] Yes
[x] No
```

feature/JM-7319: Payment Status Report

---

client/templates/juror-management/juror-record/confirm-deferral.njk
server/routes/juror-management/update/index.js
server/routes/juror-management/update/juror-update.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7008)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=437)
When deferring a juror for a second time there should be a screen warning the officer this will be a second deferral 
```
[ ] Yes
[X] No
```

When deferring a juror for a second time I should receive a warning message

---

server/routes/reporting/standard-report/standard-report.controller.js

Fixed trial selection screen for reports.
```
[ ] Yes
[x] No
```

Reports Trial Selection Fix

---

client/templates/administration/users/court-bureau-users.njk
client/templates/administration/users/users.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-7276
- select active / inactive users is slow
```
[ ] Yes
[x] No
```

update the select users radios to use the same radio group

---

server/config/express.js

N/A
update csp headers to only set upgrade-insecure-requests in production mode
```
[ ] Yes
[x] No
```

csp helmet updates

---

client/templates/juror-management/juror-record/_partials/attendance-table.njk
client/templates/juror-management/juror-record/attendance.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7426)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=454)
For court officers that have primary and satellite courts we need to make sure they have the correct relationship for what you can do when logged in as either the primary or satellite:
you can do and see everything for the other courts in your court stack except for the following:
* trial management
* attendances
* expenses
Attached is a spreadsheet the list shows in red the areas that need updating the second tab details what reports show satellite court data 
```
[ ] Yes
[X] No
```

As a system I need to make sure that satellite and primary courts work correctly

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
client/templates/reporting/deferred-list/list-by.njk
server/config/validation/report-search-by.js
server/routes/reporting/deferred-list/deferred-list.controller.js
server/routes/reporting/deferred-list/index.js
server/routes/reporting/index.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6465
Added deferred list reports.
```
[ ] Yes
[x] No
```

feature/JM-6465: Deferred List Reports

---

client/templates/pool-management/pool-overview/court-pool-overview.njk
client/templates/trial-management/trial-detail.njk
eslint.unignore.js
server/lib/reports/ballot.js
server/objects/index.js
server/routes/pool-management/pool-overview/index.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/reporting/ballot-cards/ballot-cards.controller.js
server/routes/reporting/ballot-cards/index.js
server/routes/reporting/standard-report/index.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6408)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=441)
*Acceptance Criteria*
#* On the 'Pool Record' screen, the system shall include a print button. Clicking this button shall activate a dropdown menu with an option for 'Ballot cards'.
#* When the user selects 'Ballot Cards' from the dropdown menu, the system shall generate a printable set of ballot cards for the jurors in the selected pool. This set should be formatted correctly for printing and should include necessary details as per the requirements for ballot cards.
 
 
 
 
*Validation Rules*
*Ensuring Accurate Juror Information:* The system must ensure that the information on the ballot cards (like juror number, name, and …

As a jury officer I want to generate a panel ballot report (FE)

---

server/objects/expense-record.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js

[JM-7269 - UAT - Edit expenses - Able to add more than one full day 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7269)
- Added check to see if any values have been edited on the table.
```
[ ] Yes
[x] No
```

hotfix/JM-7269 - Edit expenses - Able to add more than one full day

---

client/templates/response/detail.njk
server/routes/response/detail/detail.controller.js
server/routes/search/search.controller.js
server/routes/summons-management/summons-management.controller.js

[JM-6728 - Cannot navigate back to search results list after viewing a record from the results list 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6728)
- Added back link to summons page if the summons was searched for.
```
[ ] Yes
[x] No
```

hotfix/JM-6728 - Unable to navigate back to search from summons reply

---

server/routes/administration/users/assign-courts/assign-courts.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7201)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=460)
Log in as a system admin
select a court user with assigned courts
click assign courts
you should not see court locations that are already assigned
!image-20240502-093829.png|width=1011,height=837,alt="image-20240502-093829.png"!
!image-20240502-093856.png|width=1011,height=837,alt="image-20240502-093856.png"!
```
[ ] Yes
[X] No
```

As a system admin, court locations appear that are already assigned

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6463
Added Excused and Disqualified report.
```
[ ] Yes
[x] No
```

feature/JM-6463: Excused and Disqualified Report

---

client/templates/reporting/bureau-reports.njk
server/config/validation/report-search-by.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6412
Added electronic police check report.
```
[ ] Yes
[x] No
```

Electronic Police Check Report

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-statistics.njk
client/templates/reporting/standard-reports/date-search.njk
server/config/validation/report-search-by.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/report-export.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6450
https://centralgovernmentcgi.atlassian.net/browse/JM-6488
Added export only report functionality.
Added Pool statistics report.
Added Attendance data report.
```
[ ] Yes
[x] No
```

feature/JM-6450&6488: Pool Statistics & Attendance Data reports

---

yarn.lock

renovate thing

---

client/templates/juror-management/jurors-on-trial/trials-table.njk
server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
server/routes/reporting/jury-attendance-audit/index.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7451)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=463)
The audit report number on the jurors in trial screen should be a hyperlink, at the moment it is not.
```
[ ] Yes
[X] No
```

Jury Attendance Audit report - audit report not hyperlink

---

server/routes/trial-management/edit-trial/edit-trial.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7406)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=470)
Steps:
* create a trial with any date
* edit the trial and see todays date instead of the original
!image-20240524-093550.png|width=819,height=403,alt="image-20240524-093550.png"!
!image-20240524-093601.png|width=1002,height=852,alt="image-20240524-093601.png"!
```
[ ] Yes
[X] No
```

When editing a trial the trial date does not show the date originally set, shows todays date instead

---

client/scss/mod-custom.scss
client/templates/reporting/bureau-reports.njk
client/templates/reporting/standard-reports/court-select.njk
server/routes/reporting/index.js
server/routes/reporting/pool-ratio/index.js
server/routes/reporting/pool-ratio/pool-ratio.controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6526
Added Pool Ratio Report.
Added handling for transformed table headers.
Added handling for backlink on filter page if required.
```
[ ] Yes
[x] No
```

feature/JM-6526: Pool ratio report

---

server/routes/search/search.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JDB-5569
Fixed: Officer assigned: AUTO not displayed in response search results
```
[ ] Yes
[X] No
```

Fixed: Officer assigned: AUTO not displayed in response search results

---

client/templates/juror-management/attendance.njk
server/objects/juror-attendance.js
server/routes/juror-management/juror-management.controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6406)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=469)
*Acceptance criteria*
#* *Back* (Hyperlink)
#* *Pool attendance audit report* (Header)
#* *Print* (Tab)
#* *Attendance date*
#* *Audit number*
#* *Total*
#* *Report created*
#* *Time created*
#* *Court name*
#* *HMCTS* (Logo) Juror (Page label)
#* *Pool attendance audit report* (Header)
#* *Attendance date*
#* *Audit number*
#* *Total*
#* *Report created*
#* *Time created*
#* *Court name*
#* *Juror number*
#* *First name*
#* *Last name*
#* *Checked in*
#* *Checked out*
#* *Pool number*
#* *Trial number*
 
 
 
 
*Validation Rules (BE)*
```
[ ] Yes
[X] No
```

As a jury officer I want to generate a pool attendances report (FE)

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/court-reports.njk
client/templates/reporting/court-statistics.njk
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7498)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=479)
he system shall enable the court or bureau officer to generate a pool selection list.
 
#* The system shall error if no pool number entered.
#* Pool number (hyperlink)
#* Court name
#* Pool stage
#* Pool status
#* Pool type
#* Service start date
#* Pool number
#* Pool type
#* Service start date
#* Report created
#* Time created
#* Court name
#* Juror number (hyperlink)
#* First name
#* Last name
#* Postcode
#* Disqualified on selection
```
[ ] Yes
[X] No
```

As as Bureau or court officer I need to generate a pool selection list (FE)

---

server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7452
Fixed bug if payment audit number was empty for reports.
```
[ ] Yes
[x] No
```

hotfix/JM-7452: Fix if payment audit is empty

---

server/routes/reporting/standard-report/definitions.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7469
Updated payment status report grouped header to be sentence case.
```
[ ] Yes
[x] No
```

hotfix/JM-7469: Update payment status report grouped header

---

client/scss/mod-custom.scss
client/templates/reporting/court-reports.njk
client/templates/reporting/standard-reports/bespoke-report-body/unpaid-attendance-detailed.njk
server/config/validation/report-search-by.js
server/lib/reports/default-layout.js
server/routes/reporting/bespoke-report/bespoke-report-body.js
server/routes/reporting/bespoke-report/bespoke-report-print.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6420
Added functionality to generate an unpaid attendance report
```
[ ] Yes
[x] No
```

Feature/JM-6420- As a jury officer i want to generate a unpaid attendance report (detailed)

---

server/objects/juror-attendance.js
server/routes/juror-management/attendance/attendance.controller.js

[JM-6969 - Mark as absent doesn't work from record attendance 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6969)
- Updated absence endpoint from the FE screen.
(To test - pull down corresponding BE PR for JM-6969)
```
[ ] Yes
[x] No
```

hotfix/JM-6969 - Mark as absent doesn't work from record attendance

---

client/templates/reporting/court-reports.njk
client/templates/reporting/reprint-audit-report/find-report.njk
client/templates/reporting/reprint-audit-report/print-redirect.njk
server/routes/reporting/audit.controller.js
server/routes/reporting/reprint-audit-reports/index.js
server/routes/reporting/reprint-audit-reports/reprint-audit-report.controller.js
server/routes/reporting/standard-report/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-5906
Added functionality to reprint audit reports.
```
[ ] Yes
[x] No
```

feature/JM-5906: Reprint Audit Reports

---

client/templates/reporting/draft-audit.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7512)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=493)
!Screen Recording 2024-06-07 at 17.38.49.mov|width=1570,height=770,alt="Screen Recording 2024-06-07 at 17.38.49.mov"!
```
[ ] Yes
[X] No
```

Preview Draft Audit Report takes you to a blank screen

---

server/routes/response/detail/detail.controller.js
server/routes/search/search.controller.js
server/routes/summons-management/summons-management.controller.js

[JM-6728 - Cannot navigate back to search results list after viewing a record from the results list 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6728)
- Display search results when navigating back to summons search
```
[ ] Yes
[x] No
```

hotfix/JM-6728b - Cannot navigate back to search results list after viewing a record from the results list

---

server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7452)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=494)
The Trial Attendance report currently cannot be opened and a technical error is output. Attempted with both panelled jurors and empanelled jurors separately.
```
[ ] Yes
[X] No
```

hotfix/JM-7452: Trial Attendance Report - technical error when opening

---

client/templates/reporting/court-reports.njk
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7509)
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7510)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=495)
Juror app.
!image-20240607-152647.png|width=798,height=669,alt="image-20240607-152647.png"!
Figma:
!image-20240607-152724.png|width=608,height=573,alt="image-20240607-152724.png"!
```
[ ] Yes
[X] No
```

hotfix/JM-7509&7510: Juror amendment report title and search

---

server/routes/messaging/send-messages.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7464)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=498)
Sending messages via the Trial option throws a technical error. All other options currently work as expected.
```
[ ] Yes
[X] No
```

Selecting Trial on any message causes technical error

---

client/scss/mod-custom.scss
client/templates/reporting/_common/court-reports-nav.njk
client/templates/reporting/bureau-reports.njk
client/templates/reporting/jury-summoning-monitor/index.njk
client/templates/reporting/jury-summoning-monitor/report.njk
eslint.unignore.js
server/lib/reports/single-generator.js
server/objects/reports.js
server/routes/reporting/bespoke-report/bespoke-report-body.js
server/routes/reporting/jury-summoning-monitor/index.js
server/routes/reporting/jury-summoning-monitor/jury-summoning-monitor-print.js
server/routes/reporting/jury-summoning-monitor/jury-summoning-monitor.controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-5905)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=489)
As a Bureau Team Leader I need a report of the number of excusals (by category) so that I am informed of any trends for excusal requests
As a Bureau Team Leader I need a report of the number of awaiting information so that I can ensure current pool requests will be completed on time
As a Bureau Team Leader I need a report of the number of disqualified/ineligible jurors so that it informs future summoning ratios
```
[ ] Yes
[X] No
```

Jury summoning monitor report (FE)

---

server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7268)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=505)
Formatting of Failed to attend status on current pool status report requires changing.
```
[ ] Yes
[X] No
```

Current Pool Status - Formatting of 'failed to attend'

---

package.json
yarn.lock

Update express-rate-limit to 7.3.1

Update express-rate-limit to 7.3.1

---

client/templates/reporting/bureau-reports.njk
client/templates/reporting/standard-reports/date-search/fixed-range.njk
server/config/validation/report-search-by.js
server/objects/reports.js
server/routes/reporting/index.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/index.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/yield-performance/index.js
server/routes/reporting/yield-performance/yield-performance.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-5907)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=499)
Added Yield Performance Report.
```
[ ] Yes
[X] No
```

Report - Yield Performance Report (FE)

---

server/config/express.js

add more logging to express error-handler function

Error-handler logging

---

client/templates/pool-management/pool-overview/coroner.njk
server/objects/request-pool.js
server/routes/pool-management/coroner-court/coroner-court.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7545)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=520)
The coroners court is allowing 2 officers to summon for the same pool at the same time 
```
[ ] Yes
[X] No
```

Coroners court will let 2 officers summon for a corners court pool at the same time

---

server/routes/authentication/authentication.controller.js

Add more logs to auth for debug

add logs to auth

---

client/templates/custom-components/super-navigation/super-navigation.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-7556
https://centralgovernmentcgi.atlassian.net/browse/JM-7557
Corrected main navigation access for court/bureau users
```
[ ] Yes
[x] No
```

hotfix/JM-7556&7557: Update super navigation access

---

server/routes/authentication/authentication.controller.js

remove debug logs

---

server/components/filters/index.js

fix circular dependency filters <-> mod-utils

---

server/routes/juror-management/attendance/attendance.controller.js
server/routes/juror-management/juror-record/modify-attendance/modify-attendance.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7566)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=541)
```
[ ] Yes
[X] No
```

Modify confirmed appearance still uses pool number as part of appearance search FE Updates

---

server/lib/reports/ballot.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7570
Update ballot cards to 2x4 format.
```
[ ] Yes
[x] No
```

Feat (JM-7569) update ballot cards to 2x4 format

---

server/routes/juror-management/update/juror-update.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7584)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=547)
!Screen Recording 2024-06-17 at 12.38.47.mov|width=3456,height=2234,alt="Screen Recording 2024-06-17 at 12.38.47.mov"!
```
[ ] Yes
[X] No
```

Update juror record for bureau user not working

---

server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7178
Fix date format being used by confirm jury screen to match what BE is expecting
```
[ ] Yes
[ ] No
```

Bug (JM-7178) update date format for BE

---

client/templates/pool-management/pool-overview/court-pool-overview.njk

https://centralgovernmentcgi.atlassian.net/browse/JM-7563
update to read pool type from backend
```
[ ] Yes
[ x] No
```

hotfix/JM-7563 Pool type incorrect in pool summary

---

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7603)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=556)
```
[ ] Yes
[X] No
```

When editing an expense for approval the extra cost does not save

---

server/routes/trial-management/empanel-jury/empanel-jury.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7601
Block empanelling more jurors than required
```
[ ] Yes
[X] No
```

Bug (JM-7601) block empanelling with too many jurors

---

client/templates/juror-management/non-attendance-day.njk
server/config/validation/non-attendance-day.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7600)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=559)
!image-20240620-082823.png|width=1812,height=797,alt="image-20240620-082823.png"!
this should error at you and say ‘can not empanel more jurors than selected’
```
[ ] Yes
[X] No
```

Remove the error that stops future dates for non-attendance days

---

server/routes/reporting/standard-report/definitions.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7569
Tweak to breathing room on some report columns
```
[ ] Yes
[X] No
```

Fix (JM-7569) tweak breathing room on adjusted reports

---

server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7613)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=567)
!image-20240620-140033.png|width=1146,height=106,alt="image-20240620-140033.png"!
```
[ ] Yes
[X] No
```

Expenses - status undefined

---

server/routes/juror-management/reassign/reassign.controller.js

- fix reassign to satellite court
- ignore locCode when reassigning to same or satellite court

Fix reassign to satellite court

---

server/routes/trial-management/create-trial/create-trial.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7014)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=572)
As per description
```
[ ] Yes
[X] No
```

System allows you to create two trials at the same place with the same case number

---

client/templates/messaging/_partials/juror-list-results.njk
client/templates/messaging/export-contact-details/jurors-list.njk
server/routes/messaging/export-contact-details.controller.js
server/routes/messaging/send-messages.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7615)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=573)
!image-20240620-141256.png|width=2212,height=632,alt="image-20240620-141256.png"!
```
[ ] Yes
[X] No
```

Export contact details - if results set >500, returns "no matching results"

---

client/templates/pool-management/pool-overview/coroner.njk
server/objects/dataAccessObject.js
server/objects/request-pool.js
server/objects/request-pool.spec.js
server/routes/pool-management/coroner-court/coroner-court.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7544)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=578)
History does nothing on coroners court pool 
!image-20240612-095622.png|width=912,height=484,alt="image-20240612-095622.png"!
```
[ ] Yes
[X] No
```

History does not work on coroners court pool

---

server/lib/mod-utils.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7647)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=580)
!Screen Recording 2024-06-25 at 13.09.15.mov|width=2776,height=2032,alt="Screen Recording 2024-06-25 at 13.09.15.mov"!
```
[ ] Yes
[X] No
```

When changing a pool number on request-pool journey, the existing pool numbers are not clickable

---

client/templates/sjo-tasks/_common/search-form.njk
client/templates/sjo-tasks/undo-failed-to-attend/confirm-undo-failed-to-attend.njk
server/routes/sjo-tasks/sjo-tasks.controller.js
server/routes/sjo-tasks/undo-failed-to-attend.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7582
Fix the copy for the undo failed to attend flow.
```
[ ] Yes
[X] No
```

Bug (JM-7582) fix copy for undo failed to attend

---

server/routes/response/detail/detail.controller.js
server/routes/summons-management/summons-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7654
Block the overdue banner warning for jurors who are in complete status
```
[ ] Yes
[x] No
```

Bug (JM-7654) hide overdue banner if juror is completed

---

server/routes/documents/letters-list/letters-list.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7666
Fix dates not being sent to the BE when reprinting letters
```
[ ] Yes
[x] No
```

Bug (JM-7666) fix select-all ajax behaviour

---

client/templates/juror-management/_partials/juror-update-options.njk

N/A
Allows jurors who have been deferred to be updated back to responded
```
[ ] Yes
[X] No
```

Chore: allow deferred jurors to be updated to responded

---

server/objects/juror-record.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7612)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=595)
```
[ ] Yes
[X] No
```

Welsh flag - update juror, set welsh from Y to N, saves value as NULL instead of FALSE

---

client/scss/mod-custom.scss
client/templates/juror-management/juror-record/juror-history.njk
server/routes/juror-management/juror-record/index.js
server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-6204
Adds an option to print as pdf the juror history page.
```
[ ] Yes
[X] No
```

Feat (JM-6204) add pdf print option for juror history

---

server/config/validation/paper-reply.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7674
Tweak phone number validation to successfully reject some invalid cases
```
[ ] Yes
[X] No
```

Bug (JM-7674) fix phone validation rules

---

server/routes/summons-management/paper-reply/paper-reply.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7675
Fixes an issue when navigating backwards through the summons form.
```
[ ] Yes
[ ] No
```

Bug (JM-7675) fix internal flow navigation

---

server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7695
Fix logic for creating the list of jurors from create all in the change next due date flow.
```
[ ] Yes
[x] No
```

Bug (JM-7695) Fix check all jurors selection logic on change next due date

---

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7700
Add a missing check to see if smart card amount has been edited in the edit expense flow.
```
[ ] Yes
[X] No
```

Bug (JM-7700) fix missing condition for smart card

---

README.md

Blank line to force build
```
[ ] Yes
[ ] No
```

Blank line to force build

---

server/config/express.js
server/routes/authentication/authentication.controller.js
server/routes/authentication/azure.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7801
- add more logging to the authentication and better error handling
- add uncaughtException listener for logging crasses to app-insights..
```
[ ] Yes
[x] No
```

Add logging to authentication flow

---

server/config/validation/change-attendance-date.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7793)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=625)
```
[ ] Yes
[X] No
```

Bad Gateway on Bureau

---

server/config/express.js

N/A
fix uncaught exception logging to post to appinsights before crashing
```
[ ] Yes
[x] No
```

fix uncaught exception logging to post to appinsights before crashing

---

server/routes/juror-management/juror-record/juror-record.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7822)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=631)
```
[ ] Yes
[X] No
```

Juror history shows wrong date

---

server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7824)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=638)
```
[ ] Yes
[X] No
```

update the front end to avoid error with the description

---

server/routes/documents/pdf/letter-generator.js
server/routes/documents/print.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7839)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=639)
```
[ ] Yes
[X] No
```

Court printed letters have the address misaligned

---

server/routes/authentication/azure.controller.js

N/A
- update logger calls to call the correct crit logger function.
```
[ ] Yes
[X] No
```

Incorrect logger function being called

---

server/routes/juror-management/attendance/attendance.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7850)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=643)
```
[ ] Yes
[X] No
```

jurors-in-waiting checkin uses owner instead of loc code

---

client/templates/juror-management/_partials/history-tab.njk
client/templates/pool-management/pool-overview/pool-history.njk
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7822
- fix juror history dates
- fix pool history dates
```
[ ] Yes
[x] No
```

Amend juror and pool history dates

---

server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7869)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=647)
```
[ ] Yes
[X] No
```

cannot confirm attendance at sat court

---

server/routes/reporting/audit.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7854)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=648)
Are the audit reports not registering the mileage? it's working out the monetary value but the mileage is 0 miles... Watt, Jill 18/07
```
[ ] Yes
[X] No
```

Mileage not calculating correctly

---

server/components/filters/index.js
server/routes/juror-management/juror-record/juror-record.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7871)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=652)
```
[ ] Yes
[X] No
```

TypeError: history.forEach is not a function on selecting Attendance and Payments tab on History

---

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7873)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=653)
see screen recording 
!image-20240721-171802.png|width=1398,height=330,alt="image-20240721-171802.png"!
```
[ ] Yes
[X] No
```

edit an expense, preview, then submit throws error

---

client/templates/administration/users/create-users/confirm-details.njk
client/templates/administration/users/create-users/user-details.njk
client/templates/administration/users/edit-user.njk
client/templates/administration/users/user-record.njk
server/config/validation/create-users.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7809)
>[Sonar](https://sonarcloud.io/summary/new_code?id=juror-bureau&pullRequest=650)
!image-20240716-155339.png|width=846,height=641,alt="image-20240716-155339.png"!
```
[ ] Yes
[X] No
```

Adding expense limits to user screen

---

client/templates/administration/users/create-users/confirm-details.njk
client/templates/administration/users/create-users/user-details.njk
client/templates/administration/users/edit-user.njk
client/templates/administration/users/user-record.njk
client/templates/juror-management/_partials/heading.njk
client/templates/juror-management/_partials/history-tab.njk
client/templates/pool-management/pool-overview/pool-history.njk
server/components/filters/index.js
server/config/express.js
server/config/validation/create-users.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js
server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/pool-management/request-pool/request-pool.controller.js
server/routes/reporting/audit.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7850 - pending test
https://centralgovernmentcgi.atlassian.net/browse/JM-7822  - pending test
https://centralgovernmentcgi.atlassian.net/browse/JM-7823 - pending test
https://centralgovernmentcgi.atlassian.net/browse/JM-7869 - Pending deploy
https://centralgovernmentcgi.atlassian.net/browse/JM-7872 - Pending deploy
https://centralgovernmentcgi.atlassian.net/browse/JM-7871 - Pending deploy
https://centralgovernmentcgi.atlassian.net/browse/JM-7873 - Pending deploy
https://centralgovernmentcgi.atlassian.net/browse/JM-7809 - Pending deploy

Stabilisation3

---

server/config/validation/create-users.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7881)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=655)
Currently cannot create a new bureau user because its asking for an approval limit. Error message should be removed. 
!Screenshot 2024-07-23 at 01.15.29.png|width=1090,height=547,alt="Screenshot 2024-07-23 at 01.15.29.png"!
```
[ ] Yes
[X] No
```

Bureau user creation asking for approval limit

---

server/routes/homepage/homepage.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7896)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=659)
!image-20240723-122916.png|width=578,height=196,alt="image-20240723-122916.png"!
```
[ ] Yes
[X] No
```

Pending Juror flag on home page shows for primary court not satellite court

---

client/templates/juror-management/_partials/heading.njk
server/routes/juror-management/juror-record/juror-record.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7861
Record transferred to court does not highlight this on the record
```
[ ] Yes
[ x] No
```

Hotfix/JM-7861 Record transferred to court does not highlight this on the record

---

server/objects/juror-record.js
server/routes/juror-management/attendance/change-attendance-date/change-attendance-date.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/juror-management/update/juror-update.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7894)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=660)
MUST BE MERGED WITH https://github.com/hmcts/juror-api/pull/630
```
[ ] Yes
[X] No
```

When viewing the juror details page. I should see the attendances for the court I am logged in as not the active court the juror is at

---

server/routes/juror-management/attendance/change-times/change-times.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7902)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=663)
See screen recording.
!image-20240724-101216.png|width=1366,height=270,alt="image-20240724-101216.png"!
```
[ ] Yes
[X] No
```

Technical problem when clicking Change on attendance for a satellite court

---

client/templates/juror-management/_partials/heading.njk
client/templates/juror-management/attendance/unconfirmed/table-row.njk
server/config/validation/create-users.js
server/objects/juror-record.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js
server/routes/homepage/homepage.controller.js
server/routes/juror-management/attendance/change-attendance-date/change-attendance-date.controller.js
server/routes/juror-management/attendance/change-times/change-times.controller.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/juror-record/index.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/juror-management/manage-jurors/manage-jurors.controller.js
server/routes/juror-management/update/juror-update.controller.js
server/routes/pool-management/pool-create-manual/pool-create-manual.controller.js
server/routes/pool-management/pool-management.controller.js
server/routes/pool-management/request-pool/request-pool.controller.js
server/routes/trial-management/trial-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7881 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7888 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7896 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7861 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7847 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7894 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7880 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7902 - passed
https://centralgovernmentcgi.atlassian.net/browse/JM-7897 - pending test (no code changes?)

Stabilisation4

---

server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7915)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=667)
Unable to authorise expenses for Hove and Brighton - Error message: "sorry there is a technical problem"
User is trying to get to the page to authorise and is getting this error. 
java.lang.NullPointerException: Cannot invoke "uk.gov.hmcts.juror.api.moj.enumeration.PayAttendanceType.ordinal()" because "attendanceType" is null
at uk.gov.hmcts.juror.api.moj.service.expense.JurorExpenseServiceImpl.validateAndUpdateFinancialLossExpenseLimit(JurorExpenseServiceImpl.java:432)
at uk.gov.hmcts.juror.api.moj.service.expense.JurorExpenseServiceImpl.updateDraftFinancialLossExpense(JurorExpenseServiceImpl.java:581)
at …

INC2532622 - Unable to authorise expenses for Hove and Brighton

---

client/js/attendance.js
client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
client/templates/juror-management/approve-expenses/approve-expenses.njk
client/templates/juror-management/attendance/unconfirmed/table-row.njk
client/templates/pool-management/pool-overview/court-pool-overview.njk
server/config/express.js
server/routes/juror-management/approve-expenses/approve-expenses.controller.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/reporting/audit.controller.js

This prevents a number of crashes / errors found to be causing slight downtimes in the application.

Fixes to prevent known crashes

---

client/js/attendance.js
client/templates/juror-management/approve-expenses/_partials/approve-expenses-table.njk
client/templates/juror-management/approve-expenses/approve-expenses.njk
client/templates/juror-management/attendance/unconfirmed/table-row.njk
client/templates/pool-management/pool-overview/court-pool-overview.njk
server/config/express.js
server/routes/juror-management/approve-expenses/approve-expenses.controller.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js
server/routes/reporting/audit.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7929 (to be tested)
Stabilisation6 release
```
[ ] Yes
[ x No
```

Stabilisation6 release

---

server/lib/mod-utils.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7929)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=671)
```
[ ] Yes
[X] No
```

Code fix required to update day confirmation to include all check-in / checked-out jurors that do not have the status of JUROR 

---

server/routes/documents/letters-list/letters-list.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7950)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=675)
A crash was identified when someone tried to print letters.
This happened because we rely on a list of selected letters and this time it was somehow (?) not present.
```
[ ] Yes
[X] No
```

Application crashing on trying to print letters

---

client/templates/juror-management/_partials/attendance-tab.njk
client/templates/juror-management/_partials/history-tab.njk
client/templates/juror-management/juror-record/attendance.njk
server/components/filters/index.js
server/lib/mod-utils.js
server/routes/documents/letters-list/letters-list.controller.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7929 - pending deployment
https://centralgovernmentcgi.atlassian.net/browse/JM-7813 - pending deployment
https://centralgovernmentcgi.atlassian.net/browse/JM-7846
https://centralgovernmentcgi.atlassian.net/browse/JM-7950 - test needed for court letters (make sure can still be printed)

Stabilisation7 release

---

server/lib/mod-utils.js
server/objects/excusal-mod.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7957)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=680)
```
[ ] Yes
[X] No
```

Court can not excuse a juror unless they have a response

---

server/components/filters/index.js
server/config/validation/create-trial.js
server/config/validation/messaging.js
server/objects/create-trial.js
server/objects/panel.js
server/objects/return-jurors.js
server/routes/messaging/export-contact-details.controller.js
server/routes/messaging/send-messages.controller.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/trial-management/edit-trial/edit-trial.controller.js
server/routes/trial-management/trial-management.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7954)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=683)
re a long trial we have running - started on 3/6/24 then restarted on 25/6/24. Although it lists this as a current trial there is no data there for the jurors. In juror Management or Trial Management it justs lists it but you can't get into it to do any thing with it. The jurors on this trial last attend on 5/7/24 and didn't come back until 29/7/24 - but I can't record their attendance
Trial number - 40AD1715923&
```
[ ] Yes
[X] No
```

Trial number with special character not allowing user to access

---

server/config/validation/date-picker.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7981)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=686)
```
[ ] Yes
[X] No
```

As a court user I can not defer someone to the same day

---

server/routes/juror-management/approve-expenses/approve-expenses.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7962)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=698)
When trying to approve multiple juror's expenses at once; it approves them, but throws me out to a technical error. It does work when approving individually, and the audit report opens in a new tab, but doing in bulk seems to upset it
Raised by Caldicott, Jack 08:59 29/07
```
[ ] Yes
[X] No
```

Issue approving multiple juror's expenses 

---

client/templates/juror-management/unpaid-attendance.njk
server/routes/juror-management/unpaid-attendance/unpaid-attendance.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7991
Fixed broken date filtering on Unpaid Attendance screen as the dates were not being sent to API in correct format.
```
[ ] Yes
[x] No
```

hotfix/JM-7991: Unpaid Attendance date filtering not working

---

server/routes/documents/pdf/letter-generator.js
server/routes/documents/pdf/letter-templates.js

[JM-7977](https://centralgovernmentcgi.atlassian.net/browse/JM-7977)
Updated signature showing twice for certificate of attendance/exemption
```
[ ] Yes
[x] No
```

Hotfix/JM-7977: Update signature showing twice for certificate of attendance/exemption

---

server/app.js
server/config/express.js

- update sigterm & sigint callbacks to fast close in development
- update uncaught exceptions to flush app-insights before closing down

Update sigterm & sigint callbacks

---

server/components/filters/index.js
server/routes/documents/pdf/letter-generator.js
server/routes/documents/print.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8002)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=703)
Certificate of Attendance - "Sorry there has been a technical problem" when tying to print the certificate.
01/08 We can see that the API is returning:
"signature": "Jury Officer\n\nAn Officer of the Crown Court", for this court
This is re-printing an already printed certificate of attendance letter
```
[ ] Yes
[X] No
```

Certificate of Attendance - "Sorry there has been a technical problem" when tying to print the certificate.

---

client/templates/juror-management/_partials/attendance-tab.njk
server/components/filters/index.js
server/config/validation/messaging.js
server/lib/mod-utils.js
server/routes/trial-management/trial-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8005
Added encoded trial number links to allow for forward slashes in the trial names.
```
[ ] Yes
[x] No
```

Trial number with '/' not allowing user to access

---

client/templates/reporting/standard-reports/trial-select.njk
client/templates/trial-management/trial-detail.njk
server/routes/reporting/standard-report/standard-report.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7985)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=691)
It would also be good to include this report on the drop down on the trials page 
!image-20240802-150719.png|width=217,height=244,alt="image-20240802-150719.png"!
```
[ ] Yes
[X] No
```

Trial attendance report not showing inactive trials.

---

server/objects/expense-record.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8020
Updated the API calls to Axios for Submit Draft Expenses and Edit Expenses that are For Approval, For Re-Approval and Approved.
```
[ ] Yes
[x] No
```

hotfix/JM-8020: Replace Request-Promise with Axios - Submit Draft Expenses & Editing Expenses

---

server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/expense-record.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8024)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=708)
```
[ ] Yes
[X] No
```

App crashes on `travel over limit` if the user goes back with browser arrows

---

client/templates/summons-management/_common/details-banner-new.njk
server/routes/juror-management/juror-record/juror-record.controller.js
webpack/htmlWebpack.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8039)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=714)
This icon has been missing from the application.
!image-20240812-165327.png|width=187,height=62,alt="image-20240812-165327.png"!
```
[ ] Yes
[X] No
```

Warning icon missing from records that should display

---

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8031
Fixed travel expenses being duplicated over all edited days.
```
[ ] Yes
[x] No
```

hotfix/JM-8031: Fix travel expenses duplication

---

server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8034)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=716)
```
[ ] Yes
[X] No
```

Confirming a trial attendance can override an existing confirmed attendance

---

server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/trial-management/add-panel-members/add-panel-member.controller.js
server/routes/trial-management/create-trial/create-trial.controller.js
server/routes/trial-management/edit-trial/edit-trial.controller.js
server/routes/trial-management/empanel-jury/empanel-jury.controller.js
server/routes/trial-management/generate-panel/generate-panel.controller.js
server/routes/trial-management/returns.controller.js
server/routes/trial-management/trial-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-7910
Updated the following trial management flows to limit multiple tabs data issues;
- Create Trial
- Edit Trial
- Generate Panel
- Add Panel Members
- Empanel Jury
- Return panel/jury
```
[ ] Yes
[x] No
```

Update trial-management flows to restrict multi-tab data issues

---

client/templates/pool-management/deferral-maintenance/_partials/filters.njk
client/templates/pool-management/deferral-maintenance/index.njk
server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
server/routes/pool-management/deferral-maintenance/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8046
Updated filtering on deferral maintenance to persist through pagination.
```
[ ] Yes
[x] No
```

hotfix/JM-8046: Filtering on last name on deferral maintenance only works on the page you filter on

---

server/routes/documents/pdf/letter-generator.js
server/routes/documents/pdf/letter-templates.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8051)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=719)
sample:
!image-20240813-162710.png|width=876,height=406,alt="image-20240813-162710.png"!
```
[ ] Yes
[X] No
```

Letters have too much space between "Yours sincerely," and the signature

---

server/routes/juror-management/edit/juror-edit.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8084)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=734)
See recording for steps and result.
Was unable to find any related logs.
!Screen Recording 2024-08-16 at 14.35.49.mov|width=1818,height=976,alt="Screen Recording 2024-08-16 at 14.35.49.mov"!
```
[ ] Yes
[X] No
```

Saving juror bank details causing a 500 internal service error

---

client/templates/allocation/index.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8095)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=736)
Digital - Assign Replies - Total is at the bottom. This has not matched where it was located in heritage (Juror digital)
```
[ ] Yes
[X] No
```

Digital - Assign Replies - Total is at the bottom. This has not matched where it was located in heritage (Juror digital)

---

client/templates/administration/users/create-users/confirm-details.njk
client/templates/administration/users/create-users/user-details.njk
client/templates/administration/users/edit-user.njk
server/config/validation/create-users.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8094)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=741)
Hide "Expenses approval limits" for Court Managers and SJO's
```
[ ] Yes
[X] No
```

Hide "Expenses approval limits" for Court Managers and SJO's

---

server/routes/juror-management/edit/juror-edit.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8100)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=740)
```
[ ] Yes
[X] No
```

Unable to update juror-details if they are disqualified by age

---

server/routes/juror-management/edit/juror-edit.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8104)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=743)
```
[ ] Yes
[X] No
```

Disqualifying juror by age on editing the juror details does not save the date-of-birth

---

server/routes/documents/pdf/letter-generator.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8051

Jury officer has no space for signing letters

---

client/templates/juror-management/_partials/attendance-tab.njk
server/components/filters/index.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8110)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=754)
```
[ ] Yes
[X] No
```

Attendance and payment history shows incorrect data

---

client/templates/search/index.njk
server/routes/search/search.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8117
Added AUTO user to staff list for summons response advanced search.
```
[ ] Yes
[x] No
```

hotfix/JM-8117: Summons Response advance search on AUTO + Completed fails

---

server/routes/reporting/standard-report/standard-report-print.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8121)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=760)
```
[ ] Yes
[X] No
```

Pool ratio report should be sortable

---

server/routes/reporting/standard-report/definitions.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8134)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=763)
see attached screen recording.
Logs:
!image-20240823-142857.png|width=1495,height=353,alt="image-20240823-142857.png"!
```
[ ] Yes
[X] No
```

Non responded report fails when select to print

---

server/lib/mod-utils.js
server/objects/pool-list.js
server/routes/pool-management/pool-management.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8047)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=759)
Filtering on the service start date on the active pool screen it only applies to one page needs to apply to all pages.
Different pages have repeated results
!image-20240821-075904.png|width=2198,height=1180,alt="image-20240821-075904.png"!
```
[ ] Yes
[X] No
```

Filtering on service start date on active pool screen only applies to page you filter on

---

client/templates/juror-management/edit/juror-edit-details.njk
client/templates/summons-management/paper-reply/index.njk

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8137)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=767)
```
[ ] Yes
[X] No
```

Permission change to allow the Bureau general users to edit change name / fix error in name option

---

client/templates/trial-management/trials.njk
server/lib/reports/single-generator.js
server/routes/trial-management/index.js
server/routes/trial-management/trial-management.print.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8025)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=766)
clicking {{Print list}} does nothing.. should it print a list of the trials?
!image-20240808-105842.png|width=1624,height=114,alt="image-20240808-105842.png"!
```
[ ] Yes
[X] No
```

The "Print List" button on the trials list page does nothing

---

server/routes/response/detail/detail.controller.js
server/routes/summons-management/process-reply/process-reply.controller.js
server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
server/routes/summons-management/summons-management.controller.js

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8037)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=769)
Always asking to re-assign to another court for all deferrals, even if no address change and the postcode is in the catchment.
It always asks if you would like to re-assign to a London court, not sure if this is relevant.
```
[ ] Yes
[X] No
```

INC2553487 - Bureau asked re-assign to another court after deferring any a juror

---

client/templates/juror-management/_partials/attendance-tab.njk
client/templates/juror-management/dismiss-jurors/jurors-table.njk
client/templates/juror-management/edit/juror-edit-details.njk
client/templates/messaging/_partials/juror-list-results.njk
client/templates/messaging/export-contact-details/jurors-list.njk
client/templates/reporting/persons-attending/attendance-date.njk
client/templates/search/index.njk
client/templates/summons-management/paper-reply/index.njk
client/templates/trial-management/trials.njk
server/components/filters/index.js
server/lib/back-link.js
server/lib/mod-utils.js
server/lib/reports/ballot.js
server/lib/reports/single-generator.js
server/objects/pool-list.js
server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
server/routes/messaging/export-contact-details.controller.js
server/routes/pool-management/pool-management.controller.js
server/routes/reporting/persons-attending/persons-attending-controller.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js
server/routes/response/detail/detail.controller.js
server/routes/search/search.controller.js
server/routes/summons-management/process-reply/process-reply.controller.js
server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js
server/routes/summons-management/summons-management.controller.js
server/routes/trial-management/index.js
server/routes/trial-management/trial-management.print.controller.js

Stabilisation13
https://centralgovernmentcgi.atlassian.net/browse/JM-8117

Stabilisation13

---

client/js/print-sortable.js
client/templates/reporting/standard-reports/standard-report.njk
server/routes/reporting/bespoke-report/bespoke-report-body.js
server/routes/reporting/bespoke-report/bespoke-report-print.js
server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/standard-report-print.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/reporting/standard-report/utils.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8124
Updated the following bespoke reports to allow for sorting;
- Monthly Utilisation
- Unpaid Attendance (Detailed)
- Daily Utilisation
- Daily Utilisation (Jurors List)
- Jury Expenditure (Low Level)
```
[ ] Yes
[x] No
```

task/JM-8124: Make bespoke reports sortable

---

server/routes/administration/court-details/court-details.controller.js
server/routes/administration/courts-and-bureau/courts-and-bureau.controller.js
server/routes/administration/expense-limits-court/expense-limits-court.controller.js
server/routes/administration/non-sitting-days/non-sitting-days.controller.js
server/routes/administration/room-locations/room-locations.controller.js
server/routes/administration/users/assign-courts/assign-courts.js
server/routes/administration/users/create-users/create-users.controller.js
server/routes/administration/users/edit-user/edit-user.controller.js
server/routes/administration/users/users.controller.js

[JM-8066](https://centralgovernmentcgi.atlassian.net/browse/JM-8066)
[JM-8168](https://centralgovernmentcgi.atlassian.net/browse/JM-8168)
Updated session management to allow for multiple tabs opened for administration module where possible.
```
[ ] Yes
[x] No
```

Task/JM-8168: Update administration module session caching

---

server/routes/pool-management/convert-nil-pool/convert-nil-pool.controller.js

[JM-8172](https://centralgovernmentcgi.atlassian.net/browse/JM-8172)
The Bureau are unable to convert a NIL pool request to an active pool. When the user goes into the pool and clicks on the "convert to an active pool" button, it then takes them pool to the pool request screen but nothing has happened.
Updated controller to fetch the pool details prior to converting the pool if they are not currently stored in the session.
```
[ ] Yes
[x] No
```

hotfix/JM-8172: INC2578486 - Nil Pool request unable to be converted to an active pool

---

client/templates/juror-management/create-record-manual/juror-dob.njk
client/templates/juror-management/create-record-manual/summary.njk
client/templates/pool-management/pool-overview/bureau-pool-overview.njk
server/components/auth/index.js
server/components/auth/user-type.js
server/config/validation/record-create-manual.js
server/objects/juror-create-manual.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js
server/routes/pool-management/bureau-create-juror-record/bureau-create-juror-record.controller.js
server/routes/pool-management/bureau-create-juror-record/index.js
server/routes/pool-management/index.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8190
Added new middleware to check if bureau user has permissions to create a juror.
Updated existing court juror manual creation controller and flow to allow for bureau users to manually create and summon a juror to a pool.
```
[ ] Yes
[x] No
```

feature/JM-8190: As a Bureau Officer, I want to be able to create a Juror

---

client/templates/juror-management/create-record-manual/juror-name.njk
server/config/validation/record-create-manual.js
server/routes/juror-management/create-record-manual/create-record-manual.controller.js

[JM-8202](https://centralgovernmentcgi.atlassian.net/browse/JM-8202)
Added additional validation to the create juror record journeys for Title and DOB.
Updated date filtering on ineligible age screen to show date correctly.
```
[ ] Yes
[x] No
```

hotfix/JM-8202: Create juror record - able to enter invalid DOB and Title

---

server/config/validation/record-create-manual.js

Updated notes error message in create juror flow
```
[ ] Yes
[x] No
```

update notes error message

---

server/routes/juror-management/create-record-manual/create-record-manual.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8223
Update court create juror success banner
```
[ ] Yes
[x] No
```

hotfix/JM-8223: Update court create juror success banner

---

server/routes/juror-management/postpone/postpone.controller.js
server/routes/juror-management/update/juror-update.controller.js
server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js

[JM-8187](https://centralgovernmentcgi.atlassian.net/browse/JM-8187)
Added BVR error messages when a juror tries to defer or postpone a juror without a DOB.
General refactoring for the relevant controller files to make them more readable.
```
[ ] Yes
[x] No
```

Task/JM-8187: It should not be possible to mark a juror as deferred without a DOB

---

client/templates/juror-management/_partials/third-party-details.njk

JM-8054
https://centralgovernmentcgi.atlassian.net/browse/JM-8054
Update to descriptions for third party 'reason for completing' on Juror record page to match descriptions on response page
```
[ ] Yes
[x] No
```

JM-8054 -Bureau third party reason descriptions

---

server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
server/routes/summons-management/summons-management.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8187
Added BVR error to digital summons for deferring without DOB
```
[ ] Yes
[x] No
```

task/JM-8187b: Add defer DOB bvr to digital summons

---

server/routes/juror-management/update/juror-update.controller.js

[JM-8145](https://centralgovernmentcgi.atlassian.net/browse/JM-8145)
App has crashed twice on same call, as this call had no error handling and was receiving a 400 back from API.
```
[ ] Yes
[x] No
```

hotfix/JM-8145: Add try catch blocks to update juror deferral - available pools call

---

client/templates/juror-management/_partials/juror-update-options.njk
client/templates/juror-management/postpone/pools.njk
client/templates/summons-management/_partials/deferral-no-available-pools.njk
server/components/filters/index.js
server/routes/juror-management/postpone/postpone.controller.js
server/routes/juror-management/update/juror-update.controller.js

[JM-8224](https://centralgovernmentcgi.atlassian.net/browse/JM-8224)
Removed option to Defer/Postpone a Juror after checking them in from juror record update.
Added extra validation error messages if the user somehow bypasses the juror record update page, or the user tries to postpone from the pool record screen.
```
[ ] Yes
[x] No
```

task/JM-8224: Remove option to Defer/Postpone a Juror after checking them in

---

server/routes/trial-management/trial-management.controller.js
server/routes/trial-management/trial-management.print.controller.js

[JM-5247](https://centralgovernmentcgi.atlassian.net/browse/JM-5247)
Updated trial management table header from 'Case number' to 'Trial number'
```
[ ] Yes
[x] No
```

task/JM-5247: Update trial management table header

---

server/objects/axios-instance.js
server/objects/dataAccessObject.js
server/objects/documents.js
server/routes/documents/document-form.controller.js
server/routes/documents/exemption/exemption-list.controller.js
server/routes/documents/exemption/exemption-trials.controller.js
server/routes/documents/failed-to-attend/failed-to-attend.controller.js
server/routes/documents/letters-list/letters-list.controller.js
server/routes/documents/print.controller.js
server/routes/documents/show-cause/show-cause.controller.js

[JM-8257](https://centralgovernmentcgi.atlassian.net/browse/JM-8257)
Updated all request objects for the Documents module from Request-Promise to Axios
```
[ ] Yes
[x] No
```

task/JM-8257: Update documents module to Axios

---

server/objects/approve-jurors.js
server/objects/dismiss-jurors.js
server/objects/juror-attendance.js
server/routes/homepage/homepage.controller.js
server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
server/routes/juror-management/attendance/attendance.controller.js
server/routes/juror-management/attendance/change-times/change-times.controller.js
server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
server/routes/juror-management/juror-management.controller.js
server/routes/juror-management/manage-jurors/manage-jurors.controller.js
server/routes/pool-management/pool-overview/change-next-due-at-court/change-next-due-at-court.controller.js

[JM-8259](https://centralgovernmentcgi.atlassian.net/browse/JM-8259)
Updated Juror Management module from Request-promise to Axios.
A couple reqwuest objects are GET requests with a body, need to discuss with BE before they can be updated to Axios.
```
[ ] Yes
[x] No
```

Task/JM-8259: Update Juror Management module to Axios 

---

server/lib/mod-utils.js
server/objects/axios-instance.js
server/objects/complete-service.js
server/objects/juror-deceased.js
server/objects/juror-record.js
server/objects/juror-transfer.js
server/routes/juror-management/attendance/change-attendance-date/change-attendance-date.controller.js
server/routes/juror-management/edit/juror-edit.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/juror-management/new-name/new-name.controller.js
server/routes/juror-management/update/juror-update.controller.js
server/routes/juror-management/update/juror-update.failed-to-attend.controller.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/response/detail/detail.controller.js
server/routes/shared/complete-service/complete-service.controller.js
server/routes/summons-management/paper-reply/paper-reply.controller.js
server/routes/summons-management/summons-management.controller.js
server/routes/summons-management/update/juror-details.controller.js

[JM-8260](https://centralgovernmentcgi.atlassian.net/browse/JM-8260)
Updated Juror-Record module request objects from Request-Promise to Axios.
```
[ ] Yes
[x] No
```

task/JM-8260: Update all Juror Record module to axios

---

server/objects/reports.js
server/routes/reporting/ballot-cards/ballot-cards.controller.js
server/routes/reporting/reprint-audit-reports/reprint-audit-report.controller.js
server/routes/reporting/standard-report/standard-report.controller.js

[JM-8263](https://centralgovernmentcgi.atlassian.net/browse/JM-8263)
Updated all request objects for the Reports module from Request-Promise to Axios
```
[ ] Yes
[x] No
```

Task/JM-8263: Update Reports module to Axios

---

server/objects/messaging.js
server/routes/messaging/export-contact-details.controller.js
server/routes/messaging/send-messages.controller.js

[JM-8261](https://centralgovernmentcgi.atlassian.net/browse/JM-8261)
Updated all request objects for the Messaging module from Request-Promise to Axios
```
[ ] Yes
[x] No
```

Task/JM-8261: Update Messaging module to Axios

---

server/components/filters/index.js
server/routes/summons-management/summons-management.controller.js

[JM-8245](https://centralgovernmentcgi.atlassian.net/browse/JM-8245)
Update paper response to require addressLineOne, addressLineFour, and postcode to be processed
```
[ ] Yes
[x] No
```

task/JM-8245: Add additional validation for Address Line 4 for summons replies

---

server/routes/juror-management/edit/juror-edit.controller.js

Removed 'app' variable from juror edit controller
```
[ ] Yes
[x] No
```

task/JM-8256b: Update system codes call in juror edit controller

---

client/templates/juror-management/edit/juror-edit-details.njk
server/routes/juror-management/edit/juror-edit.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8214
Fix third party radio button being auto selected to  'Yes' when editing juror record
```
[ ] Yes
[x] No
```

JM-8214 - edit juror - fix 3rd party auto selection

---

server/routes/juror-management/juror-management.controller.js

[JM-8227](https://centralgovernmentcgi.atlassian.net/browse/JM-8227)
[JM-8274](https://centralgovernmentcgi.atlassian.net/browse/JM-8274)
Removed lock for confirming jurors in waiting until 7 days has passed.
```
[ ] Yes
[x] No
```

feature/JM-8274: As a jury officer I want to be able to confirm juror attendance for the day

---

server/objects/create-trial.js
server/objects/end-trial.js
server/objects/panel.js
server/objects/return-jurors.js
server/routes/documents/exemption/exemption-duration.controller.js
server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js
server/routes/trial-management/add-panel-members/add-panel-member.controller.js
server/routes/trial-management/create-trial/create-trial.controller.js
server/routes/trial-management/edit-trial/edit-trial.controller.js
server/routes/trial-management/empanel-jury/empanel-jury.controller.js
server/routes/trial-management/generate-panel/generate-panel.controller.js
server/routes/trial-management/returns.controller.js
server/routes/trial-management/trial-management.controller.js

[JM-8265](https://centralgovernmentcgi.atlassian.net/browse/JM-8265)
Updated all request objects for the Trial Management module from Request-Promise to Axios
```
[ ] Yes
[x] No
```

Task/JM-8265: Update Trial Management module to Axios

---

server/routes/juror-management/edit/juror-edit.controller.js
server/routes/summons-management/update/juror-details.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8252
Trim leading/trailing whitespace from name fields
```
[ ] Yes
[x] No
```

dev/JM-8252 - Trim whitespace from name fields

---

client/templates/juror-management/jurors-on-trial/confirm-attendance.njk
client/templates/juror-management/jurors-on-trial/trials-table.njk
server/objects/panel.js
server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js

https://centralgovernmentcgi.atlassian.net/browse/JM-8201
Update to allow multiple juror attendance on same attendance audit number. Correlating API changes required
```
[ ] Yes
[x] No
```

task/JM-8201: Update to allow multiple juror attendance on same attendance audit number

---

server/objects/deferral-mod.js
server/routes/juror-management/update/juror-update.controller.js

[JS-45](https://tools.hmcts.net/jira/browse/JS-45)
Updated the juror update deferral endpoint when deferring a juror into a pool
```
[ ] Yes
[x] No
```

hotfix/JS-45: Updated juror-update deferral endpoint

---

server/objects/dismiss-jurors.js
server/objects/juror-attendance.js
server/routes/juror-management/attendance/change-times/change-times.controller.js
server/routes/juror-management/attendance/confirm-attendance/confirm-attendance.controller.js
server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
server/routes/trial-management/returns.controller.js

https://tools.hmcts.net/jira/browse/JS-94
Updated 2 GET with body endpoints to new POST requests, to be supported by Axios.
```
[ ] Yes
[x] No
```

Task/JS-94: Update GET endpoints with body to support Axios requests

---

server/routes/juror-management/reassign/reassign.controller.js

[JS-23](https://tools.hmcts.net/jira/browse/JS-23)
Added backlink url to the reassign jurors screen.
```
[ ] Yes
[x] No
```

Hotfix/JS-23: Back link on reassign juror screen not working

---

client/templates/trial-management/_partials/trial-panel.njk

[JS-30](https://tools.hmcts.net/jira/browse/JS-30)
Updated local js functions for checking checkboxes on trial-detail screen.
```
[ ] Yes
[x] No
```

Hotfix/JS-30: Label on select all checkbox on Jury selection reads "0 of selected 1"

---

server/config/validation/enter-expenses.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js

[JS-17](https://tools.hmcts.net/jira/browse/JS-17)
Updated price validation for enter expenses journeys.
```
[ ] Yes
[x] No
```

Hotfix/JS-17: Price validation on enter expenses incorrect

---

server/routes/shared/complete-service/complete-service.controller.js

[JS-13](https://tools.hmcts.net/jira/browse/JS-13)
Added try catch blocks around the 'fetch juror record details' call when completing a juror's service.
```
[ ] Yes
[x] No
```

Hotfix/JS-13: Navigating directly to Incomplete Service Report from login breaks the Complete Service links.

---

client/templates/summons-management/paper-reply/index.njk
server/config/validation/paper-reply.js

[JS-22](https://tools.hmcts.net/jira/browse/JS-22)
Added maximum input length validation to paper response relationship field.
```
[ ] Yes
[x] No
```

Hotfix/JS-22: Error when max character limit for Relationship is exceeded when entering a paper juror response

---

client/templates/custom-components/sortable-table/template.njk
client/templates/documents/exemption/exemption-list.njk
client/templates/juror-management/_partials/contact-logs-tab.njk
client/templates/juror-management/dismiss-jurors/jurors-table.njk
client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
client/templates/messaging/_partials/jurors-table.njk
client/templates/trial-management/generate-panel/select-pools.njk

https://tools.hmcts.net/jira/browse/JS-131
Updated checkbox labels for various checkboxes that wouldn't activate once clicked.
```
[ ] Yes
[x] No
```

hotfix/JS-131: Updated checkbox labels to fix broken checkboxes

---

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js

https://tools.hmcts.net/jira/browse/JS-97
Added call to expense recalculation endpoint when apply default loss of earnings to all days.
Data from that call is required when generating the preview of the audit report.
```
[ ] Yes
[x] No
```

Task/JS-97: Undefined wording appearing edit payment

---

client/templates/pool-management/movement/bulk-validate.njk
client/templates/trial-management/_partials/trial-panel.njk
client/templates/trial-management/reassign-panel/confirm-reassign.njk
client/templates/trial-management/reassign-panel/select-trial.njk
server/components/filters/index.js
server/config/validation/reassign-panel.js
server/lib/mod-utils.js
server/objects/reassign-panel.js
server/routes/pool-management/pool-overview/on-call/on-call.controller.js
server/routes/reporting/standard-report/standard-report.controller.js
server/routes/trial-management/index.js
server/routes/trial-management/reassign-panel/index.js
server/routes/trial-management/reassign-panel/reassign-panel.controller.js
server/routes/trial-management/returns.controller.js
server/routes/trial-management/trial-management.controller.js

[JS-123](https://tools.hmcts.net/jira/browse/JS-123)
Add new screens and functionality to reassign panel members from one trial to another.
```
[ ] Yes
[x] No
```

Feature/JS-123: As a Court officer I want to be able to reassign jurors from one trial to another

---

client/templates/pool-management/movement/bulk-validate.njk
server/routes/pool-management/pool-overview/on-call/on-call.controller.js

[JS-121](https://tools.hmcts.net/jira/browse/JS-121)
Updated bulk validate screen to accept unique wording.
Added unique wording to the bulk on call validation screen.
```
[ ] Yes
[x] No
```

feature/JS-121b: Update wording for bulk on call validation

---

server/routes/pool-management/dismiss-jurors/dismiss-jurors.controller.js

[JS-169](https://tools.hmcts.net/jira/browse/JS-169)
Added check to see if session variable exists before accessing length.
```
[ ] Yes
[x] No
```

Hotfix/JS-169: Bad gateway error on 'generate list of jurors to dismiss' button

---

client/templates/juror-management/attendance/confirmed/confirmed.njk
client/templates/juror-management/attendance/unconfirmed/unconfirmed.njk
server/routes/juror-management/juror-management.controller.js

[JS-148](https://tools.hmcts.net/jira/browse/JS-148)
Updated locked jurors in waiting to show appearance confirmation status
```
[ ] Yes
[x] No
```

feature/JS-148b: Update locked jurors in waiting to show appearance confirmation status

---

server/routes/juror-management/juror-management.controller.js

[JS-148](https://tools.hmcts.net/jira/browse/JS-148)
Lock SJO users from seeing attendance days that aren't locked.
```
[ ] Yes
[x] No
```

feature/JS-148d: Prevent SJO users from seeing attendance days that aren't locked

---

client/js/document-letters.js
client/templates/documents/_partials/table.njk
server/routes/documents/helper/table-generator.js
server/routes/documents/letters-list/letters-list.controller.js

[JS-141](https://tools.hmcts.net/jira/browse/JS-141)
Added sorting to all generic letters.
```
[ ] Yes
[x] No
```

Task/JS-141: Add sorting to letters

---

package.json
server/app.js

JS-172
https://tools.hmcts.net/jira/browse/JS-172
App version number config for Juror front-end
```
[ ] Yes
[x] No
```

JS-172 - Bureau version number config

---

server/app.js

JS-172
https://tools.hmcts.net/jira/browse/JS-172
App version number config for Juror front-end
```
[ ] Yes
[x] No
```

JS-172a - Retrieve package settings

---

server/routes/search/search.controller.js

JS-142
https://tools.hmcts.net/jira/browse/JS-142
Fix error shown when response sent to unassigned was successful
```
[ ] Yes
[x] No
```

JS-142 - Fix error when response sent to unassigned

---

server/config/validation/paper-reply.js

JS-57
https://tools.hmcts.net/jira/browse/JS-57
Update telephone number validators to allow dashes and hyphens
```
[ ] Yes
[x] No
```

JS-57 - Update tel no validators to allow dashes and hyphens

---

client/templates/expenses/bank-details.njk
server/config/validation/bank-details.js

[JS-19](https://tools.hmcts.net/jira/browse/JS-19)
[JS-173](https://tools.hmcts.net/jira/browse/JS-173)
Add extra validation to jurors bank account holders name field.
Added. banner message to show the new field restrictions.
```
[ ] Yes
[x] No
```

Task/JS-173: Add extra validation to jurors bank account holders name field

---

client/templates/juror-management/_partials/third-party-details.njk
client/templates/response/_partials/juror-details.njk
client/templates/response/_partials/update-header.njk
client/templates/response/detail.njk
client/templates/summons-management/paper-reply/index.njk
server/config/validation/paper-reply.js
server/objects/paper-reply.js
server/routes/summons-management/paper-reply/paper-reply.controller.js
server/routes/summons-management/summons-management.controller.js
server/routes/summons-management/update/juror-details.controller.js

[JS-12](https://tools.hmcts.net/jira/browse/JS-12)
[JS-147](https://tools.hmcts.net/jira/browse/JS-147)
Added 3rd party fields to paper response entry.
```
[ ] Yes
[x] No
```

Task/JS-147: Record 3rd party name and contact details on paper response

---

client/templates/response/_partials/juror-details.njk

Revert change to how prev juror dob is shown on summons replies
```
[ ] Yes
[x] No
```

hotfix/JS-147b: Fix previous juror dob on summons reply

---

server/config/validation/paper-reply.js

JS-57:
https://tools.hmcts.net/jira/browse/JS-57
Revert change to telephone validator regex
```
[ ] Yes
[x] No
```

JS-57a - Revert change to telephone validator regex

---

client/templates/trial-management/returns/return-attendance.njk
server/routes/trial-management/returns.controller.js

Reverts hmcts/juror-bureau#874

Revert "task/JS-160: Reinstate Middle Option for Returning Jurors"

---

server/routes/pool-management/coroner-court/coroner-court.controller.js

Reverts hmcts/juror-bureau#877

Revert "hotfix/JS-129: Coroner's pool fails if no voters available"

---

server/routes/juror-management/approve-expenses/approve-expenses.controller.js
server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js

https://tools.hmcts.net/jira/browse/JS-192
Added error messaging when adding attendance at wrong court location (no juror_pool record at that court).
```
[ ] Yes
[x] No
```

Task/JS-192: Error when adding attendance at wrong court location

---

client/js/messaging-juror-select.js
client/templates/messaging/select-jurors.njk
server/routes/messaging/index.js
server/routes/messaging/send-messages.controller.js

[JS-189](https://tools.hmcts.net/jira/browse/JS-189)
Add flag to include all trial jurors who have been on the trial to sentencing date message requests
```
[ ] Yes
[x] No
```

task/JS-189: Send a sentence date message for jurors that were on a trail

---

client/templates/sjo-tasks/uncomplete-service/confirm-uncomplete.njk
server/routes/sjo-tasks/uncomplete-service.controller.js

https://tools.hmcts.net/jira/browse/JS-146
Added error message when API returns error for trying to uncomplete more than 100 jurors at once.
```
[ ] Yes
[x] No
```

task/JS-146: Error when try to uncomplete jurors

---

server/lib/back-link.js

JS-177
https://tools.hmcts.net/jira/browse/JS-177
Fix error when back link is clicked after deletion of attendance
```
[ ] Yes
[x] No
```

JS-177 - Attendance page back link error

---

package.json

JS-79
https://tools.hmcts.net/jira/browse/JS-79
Update package.json metadata
```
[ ] Yes
[x] No
```

JS-79 - Update package.json metadata

---

server/lib/back-link.js
server/routes/juror-management/approve-expenses/approve-expenses.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js

JS-178
https://tools.hmcts.net/jira/browse/JS-178
Fix back-link urls for approve-expenses and juror details pages
```
[ ] Yes
[x] No
```

JS-178 - Expenses page back link

---

client/js/messaging-juror-select.js
client/templates/messaging/select-jurors.njk
client/templates/response/_partials/juror-details.njk
client/templates/sjo-tasks/uncomplete-service/confirm-uncomplete.njk
client/templates/trial-management/returns/return-attendance.njk
package.json
server/lib/back-link.js
server/routes/juror-management/approve-expenses/approve-expenses.controller.js
server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/draft.controller.js
server/routes/juror-management/unpaid-attendance/expense-record/for-approval.controller.js
server/routes/messaging/index.js
server/routes/messaging/send-messages.controller.js
server/routes/pool-management/coroner-court/coroner-court.controller.js
server/routes/sjo-tasks/uncomplete-service.controller.js
server/routes/trial-management/returns.controller.js

Juror Bureau Release 5.2
```
[ ] Yes
[x] No
```

Release5.2

---

client/templates/juror-management/_partials/sub-nav.njk
server/routes/juror-management/juror-record/juror-record.controller.js

[JS-214](https://tools.hmcts.net/jira/browse/JS-214)
Added juror record notes tab highlight if juror has active notes.
```
[ ] Yes
[x] No
```

Task/JS-214: Added notes tab highlight if juror has active notes

---

server/routes/reporting/bespoke-report/bespoke-report-print.js

https://tools.hmcts.net/jira/browse/JS-175
Fix rounding error on the Juror expenditure (mid-level) report
```
[ ] Yes
[x] No
```

JS-175 - Rounding error on expenditure report

---

client/templates/homepage/index.njk
server/routes/index.js
server/routes/pool-management/pool-management.controller.js
server/routes/quick-links/index.js
server/routes/quick-links/quick-links.controller.js

https://tools.hmcts.net/jira/browse/JS-251
Adding the quick links to bureau homepage
```
[ ] Yes
[x] No
```

Dev/JS-251 - Quick Links Bureau Homepage

---

client/templates/search/index.njk

[JS-212](https://tools.hmcts.net/jira/browse/JS-212)
Updated wording and sorting whens earching for completed replies.
```
[ ] Yes
[x] No
```

task/JS-212: Update sorting and message for completed replies search

---

client/templates/expenses/_partials/food-and-drink.njk

[JS-268](https://tools.hmcts.net/jira/browse/JS-268)
Updated FE expense subsistence fields to only allow for Yes or No.
```
[ ] Yes
[x] No
```

Task/JS-268: Enhance Subsistence Calculation - Auto Calculate Court & Travel Time

---

server/routes/date-picker/index.js

https://tools.hmcts.net/jira/browse/JS-209
https://tools.hmcts.net/jira/browse/JS-288
Fixed date picker bank holidays named route, so that it does not match the administration bank holidays route.
```
[ ] Yes
[x] No
```

hotfix/JS-288: Fix date picker bank holidays named route

---

client/templates/administration/expense-limits.njk
client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
client/templates/juror-management/juror-record/_partials/attendance-table.njk
server/components/filters/index.js
server/config/validation/update-expense-rates.js
server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js

https://tools.hmcts.net/jira/browse/JS-281
When a juror has over 201 attendance days the system shall pay the juror a higher rate of 228.6 for full days and 114.03 for half days.
```
[ ] Yes
[x] No
```

Task/JS-281: When a juror is over 201 attendance days pay a higher rate

---

package.json

Update app version to 5.4
```
[ ] Yes
[x] No
```

Update app version 5.4

---

client/templates/_errors/data-mismatch.njk
server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
server/routes/juror-management/edit/juror-edit.controller.js
server/routes/juror-management/expenses/edit-bank-details/edit-bank-details.controller.js
server/routes/juror-management/expenses/expenses.controller.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js

JS-72 - https://tools.hmcts.net/jira/browse/JS-72
Additional safeguards for url changes when using cached session data
```
[ ] Yes
[x] No
```

JS-72 - Additional safeguards using cached session data

---

client/js/summoning-progress.js
client/scss/summoning-progress.scss
client/templates/pool-management/summoning-progress/index.njk
client/templates/pool-management/summoning-progress/table/summoning-progress-table.njk
server/routes/pool-management/summoning-progress/summoning-progress.controller.js
webpack/htmlWebpack.js

https://tools.hmcts.net/jira/browse/JS-233
Added values onto the summoning progress bars
```
[ ] Yes
[x] No
```

Task/JS-233: Display numbers on Summoning Progress bars

---

server/routes/reporting/standard-report/definitions.js
server/routes/reporting/standard-report/standard-report.controller.js

https://tools.hmcts.net/jira/browse/JS-320
Add handling for extra column in reasonable adjustments report when printing to pdf
```
[ ] Yes
[x] No
```

Hotfix/JS-320: Reasonable Adjustments Report Print fix

---

client/templates/trial-management/trials.njk
server/routes/trial-management/index.js
server/routes/trial-management/trial-management.controller.js
server/routes/trial-management/trial-management.print.controller.js

Added ability to search for a trial from the trials screen.
https://tools.hmcts.net/jira/browse/JS-289
```
[ ] Yes
[x] No
```

task/JS-289: Add search field on trials screen

---

client/templates/custom-components/date-picker/template.njk
client/templates/juror-management/attendance.njk
client/templates/juror-management/jurors-on-trial/list-of-trials.njk
server/routes/juror-management/juror-management.controller.js
server/routes/juror-management/jurors-on-trial/jurors-on-trial.controller.js

https://tools.hmcts.net/jira/browse/JS-285
Added date picker to record attendance screens to easily navigate to different dates.
```
[ ] Yes
[x] No
```

Task/JS-285: As a court officer I want to navigate to previous dates easier form the record attendance screen

---

client/templates/juror-management/juror-record/details.njk
client/templates/juror-management/reassign/pools.njk
client/templates/summons-management/process-reply/reassign-before-process.njk
server/objects/juror-record.js
server/routes/juror-management/edit/index.js
server/routes/juror-management/edit/juror-edit.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/juror-management/reassign/reassign.controller.js

https://tools.hmcts.net/jira/browse/JS-208
Added new screens to reassign a juror to a new pool if they have been moved outside of the catchment area from juror record (BUREAU ONLY).
```
[ ] Yes
[x] No
```

Task/JS-208: Flag when a postcode change moves a juror into a different court catchment area (juror record)

---

client/templates/messaging/_partials/pools-table.njk
client/templates/messaging/find-jurors.njk
client/templates/messaging/select-pool.njk
server/lib/mod-utils.js
server/routes/messaging/index.js
server/routes/messaging/send-messages.controller.js

https://tools.hmcts.net/jira/browse/JS-295
Add active pools list selection to messaging module
```
[ ] Yes
[x] No
```

Task/JS-295: Add active pools list selection to messaging module

---

client/templates/juror-management/search/results-list.njk
server/routes/juror-management/search/search.controller.js

https://tools.hmcts.net/jira/browse/JS-211
Display juror email address in search results for Bureau officers
```
[ ] Yes
[x] No
```

JS-211 - Email address displayed in juror search results for Bureau

---

client/templates/juror-management/edit/juror-edit-details.njk
client/templates/juror-management/juror-record/details.njk
server/routes/juror-management/edit/juror-edit.controller.js

https://tools.hmcts.net/jira/browse/JS-270
Add living overseas flag to juror record and error juror record
```
[ ] Yes
[x] No
```

task/JS-270: Add living overseas flag to juror record

---

charts/juror-bureau/Chart.yaml

helm: update to use oci

---

client/templates/trial-management/trial-detail.njk
server/routes/administration/judges/judges.controller.js
server/routes/administration/non-sitting-days/non-sitting-days.controller.js
server/routes/juror-management/edit/juror-edit.controller.js
server/routes/juror-management/update/juror-update.failed-to-attend.controller.js
server/routes/pool-management/create-pool/summon-citizens/summon-citizens.controller.js
server/routes/reporting/pool-ratio/pool-ratio.controller.js
server/routes/trial-management/add-panel-members/add-panel-member.controller.js
server/routes/trial-management/edit-trial/edit-trial.controller.js
server/routes/trial-management/trial-management.controller.js

https://tools.hmcts.net/jira/browse/JS-201
Add messages for BVR errors
```
[ ] Yes
[x] No
```

JS-201 - Update Juror Record and Summons Management error messaging

---

client/templates/pool-management/_common/select-court.njk
client/templates/pool-management/deferral-maintenance/index.njk
client/templates/pool-management/deferral-maintenance/pools.njk
server/objects/pool-management.js
server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
server/routes/pool-management/deferral-maintenance/index.js

https://tools.hmcts.net/jira/browse/JS-291
Added option to move juror to another court from deferral maintenance
```
[ ] Yes
[x] No
```

Task/JS-291: Add option to move juror to another court from deferral maintenance

---

server/config/validation/court-details.js

[JS-310](https://tools.hmcts.net/jira/browse/JS-310)
Limit cost centre to 5 characters
```
[ ] Yes
[x] No
```

task/JS-310: Limit cost centre to 5 characters

---

client/templates/pool-management/pool-overview/court-pool-jurors.njk
client/templates/trial-management/_partials/trial-panel.njk
server/objects/juror-attendance.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
server/routes/pool-management/pool-overview/index.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/trial-management/add-non-attendance-day/add-non-attendance-day.controller.js
server/routes/trial-management/add-non-attendance-day/index.js
server/routes/trial-management/index.js
server/routes/trial-management/trial-management.controller.js

https://tools.hmcts.net/jira/browse/JS-312
Add option to add non-attendance days in bulk for jurors from either pool overview or trial details screen.
Refactored the bulk process actions on pool overview to reduce the large amount of code duplication for very similar flows.
```
[ ] Yes
[x] No
```

Task/JS-312: Add non attendance days in bulk for certain jurors

---

client/templates/pool-management/_common/select-court.njk
client/templates/pool-management/deferral-maintenance/index.njk
client/templates/pool-management/deferral-maintenance/pools.njk
client/templates/pool-management/pool-overview/court-pool-jurors.njk
client/templates/trial-management/_partials/trial-panel.njk
package.json
server/config/validation/court-details.js
server/objects/juror-attendance.js
server/objects/pool-management.js
server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js
server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
server/routes/pool-management/deferral-maintenance/index.js
server/routes/pool-management/pool-overview/index.js
server/routes/pool-management/pool-overview/pool-overview.controller.js
server/routes/trial-management/add-non-attendance-day/add-non-attendance-day.controller.js
server/routes/trial-management/add-non-attendance-day/index.js
server/routes/trial-management/index.js
server/routes/trial-management/trial-management.controller.js

[JS-265](https://tools.hmcts.net/jira/browse/JS-265)
[JS-291](https://tools.hmcts.net/jira/browse/JS-291)
[JS-312](https://tools.hmcts.net/jira/browse/JS-312)
Juror Bureau Release 5.6
```
[ ] Yes
[x] No
```

Release5.6

---

client/templates/juror-management/_partials/heading.njk
client/templates/juror-management/_partials/juror-details-banner.njk
client/templates/juror-management/edit/juror-edit-deferral.njk
client/templates/juror-management/juror-record/notes-edit.njk
client/templates/juror-management/juror-record/overview.njk
server/routes/juror-management/edit/juror-edit.controller.js
server/routes/juror-management/juror-record/juror-record.controller.js

https://tools.hmcts.net/jira/browse/JS-216
Updated change deferral flow to show the juror record details banner.
```
[ ] Yes
[x] No
```

Task/JS-216: See the full juror record when updating a deferral

---

client/templates/homepage/index.njk

[JS-65](https://tools.hmcts.net/jira/browse/JS-65)
Updated home page quick links for court users.
```
[ ] Yes
[x] No
```

task/JS-65: Update home page quick links for court

---

server/routes/juror-management/juror-record/juror-record.controller.js

[JS-323](https://tools.hmcts.net/jira/browse/JS-323)
Limited cached data check to juror record notes only.
```
[ ] Yes
[x] No
```

hotfix/JS-323: Error when adding notes to summons reply

---

server/routes/juror-management/expenses/non-attendance-day/non-attendance-day.controller.js

https://tools.hmcts.net/jira/browse/JS-317
Redirect to error page if  juror/pool number is changed in URL for add non-attendance page
```
[ ] Yes
[x] No
```

JS-317 -  handle  juror/pool number change in URL for add non-attendance

---

server/objects/paper-reply.js

https://tools.hmcts.net/jira/browse/JS-300
Save email address as null in database instead of empty string
```
[ ] Yes
[x] No
```

JS-300 - Save empty email address as null

---

server/routes/juror-management/attendance/attendance.controller.js

https://tools.hmcts.net/jira/browse/JS-368
Fixed issue where 'Run police check' was not showing when checking jurors in if they had not been police checked.
```
[ ] Yes
[x] No
```

hotfix/JS-368: 'Run police check' when checking in jurors not showing

---

client/templates/homepage/index.njk

[JS-350](https://tools.hmcts.net/jira/browse/JS-350)
Added advanced juror search link to home screen for bureau users.
```
[ ] Yes
[x] No
```

Task/JS-350: Add advanced juror search to homepage for bureau users

---

client/templates/juror-management/_partials/third-party-details.njk

[JS-357](https://tools.hmcts.net/jira/browse/JS-357)
Hide third party details segment when the juror has no third part contact details.
```
[ ] Yes
[x] No
```

Task/JS-357: Hide third party details segment when irrelevant

---

client/templates/allocation/index.njk
server/routes/allocation/allocation.controller.js

[JS-364](https://tools.hmcts.net/jira/browse/JS-364)
Add 'Awaiting Information' column to the table on Assign Replies screen
```
[ ] Yes
[x] No
```

Task/JS-364: Show 'Awaiting Information' on Assign Replies screen

---

server/config/validation/paper-reply.js

[JS-349](https://tools.hmcts.net/jira/browse/JS-349)
Add validation and error messages for leading and trailing spaces in first and last names
```
[ ] Yes
[x] No
```

Task/JS-349: As a Bureau user I do not want to accidentally leave a leading space in the juror first name

---

server/config/validation/paper-reply.js
server/routes/juror-management/edit/juror-edit.controller.js

JS-349 https://tools.hmcts.net/jira/browse/JS-349
Change name validation rule order, preserve edited details for 'fix' name only
```
[ ] Yes
[x] No
```

JS-349-Fix -  Update validation order / preserve edit changes

---

server/components/auth/index.js
server/components/auth/user-type.js
server/routes/authentication/authentication.controller.js

https://tools.hmcts.net/jira/browse/JS-416
Create new permission type super user
```
[ ] Yes
[ x] No
```

task/JS-416 Update to handle new super user permission

---

client/templates/juror-management/manage-jurors.njk

https://tools.hmcts.net/jira/browse/JS-412
Remove print button from manage-jurors page
```
[ ] Yes
[x] No
```

JS-412 - Manage jurors - remove redundant print button

---

server/routes/homepage/homepage.controller.js
server/routes/homepage/index.js

https://tools.hmcts.net/jira/browse/JS-469
Limit court dashboard to super user permission only.
```
[ ] Yes
[x] No
```

task/JS-469: Limit court dashboard to super user permission only

---

client/templates/response/_partials/eligibility.njk
client/templates/summons-management/paper-reply/eligibility.njk
server/config/validation/paper-reply.js
server/routes/juror-management/update/juror-update.responded.controller.js
server/routes/response/detail/detail.controller.js
server/routes/summons-management/paper-reply/paper-reply.controller.js
server/routes/summons-management/summons-management.controller.js
server/routes/summons-management/update/eligibility.controller.js

[JS-439](https://tools.hmcts.net/jira/browse/JS-439)
Added eligibility comments boxes to each of the 5 eligibility questions when entering a paper response.
```
[ ] Yes
[x] No
```

Task/JS-439: Add comments around the 5 juror eligibility question - Paper responses

---

client/templates/juror-management/juror-record/attendance.njk
server/routes/documents/document-form.controller.js
server/routes/documents/show-cause/index.js

[JS-449](https://tools.hmcts.net/jira/browse/JS-449)
Updated routing for show cause letter cancel link to stop bug on cancelling from juror record.
```
[ ] Yes
[x] No
```

task/JS-449: Update print show cause letter routing

---

client/templates/expenses/default-expenses.njk

https://tools.hmcts.net/jira/browse/JS-443
Automatically update draft expenses with defaults - remove option checkbox from default expenses page
```
[ ] Yes
[x] No
```

JS-443 - Automatically update draft expenses with defaults

---

client/js/expenses-summary.js

[JS-528](https://tools.hmcts.net/jira/browse/JS-528)
Fix pay attendance radios for editing approved expenses.
```
[ ] Yes
[x] No
```

hotfix/JS-528: Fix pay attendance radios for editing approved expenses

---

client/templates/pool-management/pool-overview/bureau-pool-jurors.njk
client/templates/pool-management/pool-overview/bureau-pool-overview.njk
client/templates/pool-management/pool-overview/pool-summary.njk
server/routes/pool-management/pool-overview/bureau-view.js
server/routes/pool-management/pool-overview/paginate-jurors-list.js
server/routes/pool-management/pool-overview/pool-overview.controller.js

[JS-225](https://tools.hmcts.net/jira/browse/JS-225)
Updated pool overview so that bureau officers can see jurors when searching a pool that is in the court's possession.
```
[ ] Yes
[x] No
```

Task/JS-225: Update Bureau Pool Overview - Court owned pools

---

client/templates/homepage/court-dashboard/dashboard.njk
client/templates/homepage/court-dashboard/widgets/alerts.njk
server/lib/mod-utils.js
server/routes/homepage/dashboard/definitions.js
server/routes/homepage/homepage.controller.js
server/routes/homepage/index.js

https://tools.hmcts.net/jira/browse/JS-516
Add additional information to the court dashboard -unlock for all court users.
```
[ ] Yes
[x] No
```

task/JS-516: Add additional information to the court dashboard

---

server/routes/messaging/send-messages.controller.js

https://tools.hmcts.net/jira/browse/JS-385
Updated Sentencing Invite email to include all jurors previously on trial.
```
[ ] Yes
[x] No
```

task/JS-385: Invite to sentence email not including all jurors previously on trial

---

server/config/validation/date-picker.js
server/routes/juror-management/edit/juror-edit.controller.js

[JS-541](https://tools.hmcts.net/jira/browse/JS-541)
Added extra validation on juror edit screen. User will no longer be asked to disqualify a juror due to age if they are already disqualified.
```
[ ] Yes
[x] No
```

task/JS-541: Add extra edit DoB validation on juror edit
