config/development.json, config/production.json, config/test.json, server/lib/appinsights.js
Default app-insights-connection-string to "" in json files to allow test for empty string to be used in lib/appinsights.js
```
[ ] Yes
[x] No
```
=> alter insights again

client/templates/completed.njk, client/templates/inbox.njk, client/templates/pending.njk, client/templates/search/index.njk, server/objects/responses.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6575
Fixed dates on Todo, waiting info and processed tables
Also fixed the links in these tables to go to the relevant reply type pages, e.g. paper and digital
The PR will need to be deployed with the backend with fixes that work with it
```
[ ] Yes
[ x] No
```
=> hotfix/JM-6575 Fixing dates on Todo, waiting info and processed pages

server/config/validation/juror-bulk-transfer.js, server/config/validation/juror-bulk-transfer.spec.js, server/lib/mod-utils.js, server/routes/juror-management/postpone/postpone.controller.js, server/routes/juror-management/reassign/reassign.controller.js, server/routes/juror-management/update/juror-update.transfer.controller.js, server/routes/pool-management/pool-overview/pool-overview.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6611
With the new pool overview, we don't necessarily have juror details for FE validation, or for error messaging when something goes wrong. This change removes FE validation relying on juror data we might not have, and makes it so that we pull the juror name is pulled from the validation API.
This requires https://github.com/hmcts/juror-api/pull/93 to work, but will be no worse because it currently crashes for lack of data where it's currently looking.
```
[ ] Yes
[ ] No
```
=> Feature (JM-6611) pull juror name from validate movement API for errors

client/templates/juror-management/juror-record/details.njk
[JM-5746](https://centralgovernmentcgi.atlassian.net/browse/JM-5746)
Allow the edit of a juror's details from their Juror Record even if a summons reply has been received and processed.
```
[ ] Yes
[x] No
```
=> hotfix/JM-5746 - Cannot edit juror details from juror record while a summons reply is active 

server/config/environment/production.js
N/A
Production should read logs from stdout as opposed to just transport them to the api like before.
```
[ ] Yes
[x] No
```
=> add logging to stdout back into production

client/templates/trial-management/trial-detail.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-6823
‘Generate panel’ button should not be visible, only ‘Add panel members’
```
[ ] Yes
[ x] No
```
=> JM-6823:  'generate panel' button should not be visible

server/config/validation/change-attendance-date.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6814
Fix validation crash if selectedJurors is null on bulk update next due date
```
[ ] Yes
[x] No
```
=> Bug (JM-6814) fix crash on empty bulk next due at court

client/templates/administration/judges/judges.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-6945
Changed condition in nunjuck file for allowing deletion of judges, was mistakingly set5 to only show when judge was 'inactive' and not when they hadn't been used.
```
[ ] Yes
[x] No
```
=> hotfix/JM-6945: Updated adminstration delete judge condition

client/templates/response/_partials/reasonable-adjustments.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-6671
Removed 'check can accommodate button' if response status is closed
```
[ ] Yes
[x] No
```
=> hotfix/JM-6671: Removed 'check can accommodate button' if response status is closed

client/templates/pool-management/pool-overview/court-pool-jurors.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-5051
Makes it so that court users can see jurors they own in bureau owned pools.
```
[ ] Yes
[X] No
```
=> Bug (JM-5051) fix court visibility of court owned jurors in inactive pools

client/templates/custom-components/letter-flow/redirect.njk, client/templates/juror-management/juror-record/attendance.njk, server/routes/documents/print.controller.js, server/routes/documents/show-cause/show-cause.controller.js, server/routes/juror-management/juror-record/juror-record.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6827
The print functionality was breaking for show cause letters due to a change made to the endpoint requirements. The payload sent to the endpoint has now been correctly updated with the juror number and absent date. If printing a letter from the juror record, the letter will show the most recent absent date.
```
[ ] Yes
[x] No
```
=> hotfix/JM-6827: show cause letter issues

client/templates/pool-management/pool-overview/bureau-pool-overview.njk, server/routes/pool-management/pool-overview/pool-overview.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6934
Removed access to buttons on pool overview for Bureau users onc epool has been transferred to the court.
Locked view, and show message that pool has been transferred. (Spoke to Liam about this)
```
[ ] Yes
[x] No
```
=> hotfix/JM-6934: Locked Bureau pool view once pool transferred to court

client/templates/juror-management/_common/juror-management-nav.njk, server/routes/juror-management/approve-expenses/index.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6776
Locked expense approval to court managers only
```
[ ] Yes
[x] No
```
=> hotfix/JM-6776: Lock expense approval to court managers only

client/templates/pool-management/pool-overview/_partials/sub-nav.njk, server/routes/pool-management/pool-overview/pool-overview.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-6933
Hide pool history tab for all court users until the pool has been transferred to court.
```
[ ] Yes
[x] No
```
=> Court Users - Hide pool history tab until transferred to court

client/js/attendance.js
N/A
- fix bug where count was adding wrong because the table row was being added to the wrong parend
```
[ ] Yes
[x] No
```
=> fix jurors attending table count

client/templates/juror-management/juror-record/overview.njk
[JM-7011 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7011)
Fixed unnecessary '-' before 'None' reasonable adjustment.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7011 - Unnecessary has leading '-'

client/templates/layouts/govuk_template.njk
[JM-7077 - Users requesting a home page button 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7077)
- Added homepage link to the HMCTS serviceName on the top left as discussed with Liam.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7077 - Users requesting a home page button

client/templates/juror-management/juror-record/overview.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7115)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-bureau&pullRequest=%pullRequestNumber%)
‘None’ doesn’t allow you to proceed, 'N - None' does
!Screenshot 2024-04-22 at 12.14.24.png|width=350,height=532,alt="Screenshot 2024-04-22 at 12.14.24.png"!
```
[ ] Yes
[X] No
```
=> Reasonable adjustments contains None and N - None

client/templates/response/detail.njk
[JM-7126 - UAT - No back button on after clicking on a summons reply 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7126)
- Added a Back link on the summons reply page.
As discussed with Liam, the 'Back' link will take the user back to their inbox page.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7126 - Missing back link on Summons Reply page

server/routes/summons-management/index.js, server/routes/summons-management/process-reply/process-reply.controller.js
[JM-7129 - UAT - letting Bureau process a reply once it is in court control 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7129)
- Add check to see if the juror's and current user's owner values match.
The only way I could replicate this bug was by (as a Court user) going to a court-owned juror's summons reply, click on the Process reply button (the button itself is only available if the juror's owner matches the user's auth owner value), then copying the link in the URL bar, log out and log in as a Bureau user, and pasting the link in the browser.
Spoke to Liam - he mentioned this bug came up during UAT after a data load (to which I have no access to).
The fix prevents unauthorised access to the 'Process reply' process regardless by checking the owner values.
**Does this PR …
=> hotfix/JM-7129 - Bureau able to process a court-owned reply

client/templates/juror-management/juror-record/_partials/attendance-table.njk
[JM-6795 - Data ordering on the attendance table on juror over view sort incorrectly 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-6795)
- Fixed date data-sorting-value format to correctly sort by date.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7033 -Incorrect date sorting on attendance table (Juror record)

client/templates/pool-management/pool-overview/court-pool-overview.njk, server/routes/pool-management/pool-overview/edit/edit-pool.controller.js, server/routes/pool-management/pool-overview/pool-overview.controller.js
[JM-7153 - No edit pool button for court users on pool requests or active pools 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7153)
Court users should be able to edit requested and active pools, regardless of the pool's owner.
- Added 'Edit pool' button for Court users.
BE PR: https://github.com/hmcts/juror-api/pull/278
```
[ ] Yes
[x] No
```
=> hotfix/JM-7153 - Missing 'Edit pool' button for Court users

client/templates/messaging/export-contact-details/details-to-export.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7169)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=311)
All deselected by default. In heritage, they are all selected by default. Is that correct - is it more useful to users to have them all selected?
!image-20240430-103317.png|width=676,height=778,alt="image-20240430-103317.png"!
!image-20240430-103458.png|width=1381,height=261,alt="image-20240430-103458.png"!
```
[ ] Yes
[X] No
```
=> Export details - data items all deselected by default

client/templates/juror-management/search/index.njk, server/routes/juror-management/search/search.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7182)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=315)
Single juror result shows a table but should redirect to the juror record
!image-20240430-162303.png|width=1543,height=933,alt="image-20240430-162303.png"!
```
[ ] Yes
[X] No
```
=> Single juror record on search does not redirect to the juror record page

client/templates/administration/users/create-users/confirm-details.njk
N/A
fix a comma breaking a nunjucks template for gone missing
```
[ ] Yes
[x] No
```
=> fix a missing comma on a nunjucks macro

server/config/validation/document-form.js
[JM-7159 - Wrong input validation 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7159)
- Amended validation logic to only run depending on user's selected option.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7159 - Wrong input validation

client/templates/layouts/govuk_template.njk, client/templates/sign-in.njk, config/environment.template.json, server/lib/session-config.js, server/routes/authentication/azure.controller.js, server/routes/authentication/index.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6386)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=329)
acceptance criteria:
|JMUMM 03:|The system shall enable administrators, court and bureau officers to sign in to the system|
|Requirement Description|The system shall enable administrators, court and bureau officers to sign in to the system
       I.         The system shall display a sign in and button and the following message ‘If you need access to this service. Speak to your manager or contact Crown IT support (hyperlink from contact to support)
     II.         The system shall use Microsoft single sign on and ask the officer to enter their email and password the first time they sign on
    III.         The system shall …
=> Login to Azure - As a user I need to be able to sign in to the system (FE)

client/templates/administration/users/create-users/confirm-details.njk, server/routes/administration/users/create-users/create-users.controller.js
[JM-7123 - If I try to create a user with an email that is already recorded against a user: "Sorry, there is a technical problem" 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7123)
- Added FE error handling for when an email address is already in use.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7123 - Existing email FE error handling

client/templates/juror-management/juror-record/attendance.njk
[JM-7214 - Can set next due at court date for jurors not in 'summoned' status from Juror Record 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7214)
- Made 'Change' link only available if the Juror has status "Responded".
```
[ ] Yes
[x] No
```
=> hotfix/JM-7214 - 'Summoned' jurors should not have their next due changed (Juror record).

server/routes/messaging/send-messages.controller.js
[JM-7165 - Sending juror messages causing technical error 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7165)
- Corrected wrongly parsed JWT token for API call.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7165 - Sending juror messages causing technical error

client/templates/custom-components/super-navigation/super-navigation.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7246)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=336)
[https://juror.staging.apps.hmcts.net/search|https://juror.staging.apps.hmcts.net/search] page has 2 links with text “Advanced Search”
!image-20240508-134251.png|width=1294,height=779,alt="image-20240508-134251.png"!
```
[ ] Yes
[X] No
```
=> 2 links with text "Advanced search" on search page

client/templates/response/_partials/call-logs.njk, client/templates/response/_partials/notes.njk, client/templates/summons-management/_partials/signature.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7225)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=330)
BAU regression test {{Scenario Outline: Change postcode - old postcode in >1 loc_code SHOWS CHANGE COURT}}
Juror is summoned with postcode {{SY2 6LU}} - SY2 exists in court_catchment_area in 2 loc_codes:
!image-20240507-101322.png|width=638,height=170,alt="image-20240507-101322.png"!
When I search for this response, then select the response from search results, I get 
!image-20240507-101401.png|width=516,height=116,alt="image-20240507-101401.png"!
Same result if I nav to the response via the juror record.
Logs reporting the following, but Im not sure whether that is a red herring: Juror: 045200185. Cannot find paper response …
=> Internal server error where juror's postcode exists in >1 court_catchment_area

client/templates/juror-management/expense-record/_partials/expenses-table-macros.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7262)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=342)
When returning a jury and confirming attendance, the jurors attendance details on the unpaid attendance screen appear incorrect. 
```
[ ] Yes
[X] No
```
=> Attendance details on unpaid attendance incorrect after returning jury

client/templates/response/_partials/juror-details.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7252)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=344)
The ‘Email’ field on the Juror details doesn’t have the same structure as the other fields. From the tests it looks like it did at some point but the ID which was 'jurorEmailAddress' has been lost.
!image-20240509-100138.png|width=490,height=191,alt="image-20240509-100138.png"!
```
[ ] Yes
[X] No
```
=> Summons Reply - Juror details Email field doesn't have the same structure

server/routes/reporting/standard-report/utils.js
[JM-7219 - Time created incorrect on reports 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7219)
- Fixed wrongly parsed time.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7219 - Time created incorrect on reports

client/templates/response/_partials/update-header.njk
[JM-7205 - Bureau user (non manager) can assign response to another user 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7205)
- Restricted the 'Send to colleague...' link to the assigned user only and Bureau managers.
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> hotfix/JM-7205 - Bureau user (non-manager) can assign response to another user

server/config/validation/end-trial.js, server/config/validation/end-trial.spec.js, server/routes/trial-management/trial-management.controller.js
[JM-7277 - End trial date can be set before trial start date 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7277)
- Added check to see if Trial end date is before start date.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7277 - End trial date can be set before trial start date

server/routes/reporting/standard-report/standard-report.controller.js
[JM-7266 - Non Responded List - Bureau owned pools outputting technical error 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7266)
- Added filter for court users to filter out Bureau-owned courts.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7266 - Non Responded List - Bureau owned pools outputting technical error

client/templates/juror-management/_partials/juror-update-options.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7236)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=371)
Currently the option to reassign Jurors is only possible for Bureau officers when updating a juror record.
!MicrosoftTeams-image.png|width=1341,height=2097,alt="MicrosoftTeams-image.png"!
```
[ ] Yes
[X] No
```
=> Non-Bureau users can not reassign jurors

server/routes/juror-management/expenses/enter-expenses/enter-expenses.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7401)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=401)
Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [2] in public org.springframework.http.ResponseEntity<uk.gov.hmcts.juror.api.moj.controller.request.expense.CombinedExpenseDetailsDto<uk.gov.hmcts.juror.api.moj.controller.response.expense.ExpenseDetailsForTotals>> uk.gov.hmcts.juror.api.moj.controller.JurorExpenseController.calculateTotals(java.lang.String,java.lang.String,uk.gov.hmcts.juror.api.moj.controller.request.expense.CalculateTotalExpenseRequestDto): [Field error in object 'calculateTotalExpenseRequestDto' on field 'expenseList[0]': rejected value [null]; codes …
=> When entering draft expenses and clicking save and back an invalid payload is set to the BE code which leads to a 400 being returned

client/templates/reporting/court-reports.njk, server/config/validation/report-search-by.js, server/routes/reporting/standard-report/definitions.js, server/routes/reporting/standard-report/index.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6490)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=443)
|JMRSM 15:|The system shall enable officers to generate an unpaid attendance summary report|
|Requirement Description|The system shall enable officer to generate an unpaid attendance summary reprort.
 
#* Date from
#** Must be a real date
#* Date to
#** Must be a real date
#** Must be after attendance from
#* Date from
#* Date to
#* Total unpaid attendances
#* Report created
#* Time created
#* Court name
#* Juror number (hyperlink)
#* First name
#* Last name
#* Total (per day)
Dev note
The list contain juror with unpaid attendances for that court for the days in the date range|
|Owner|Product Owner|
|Additional Details|*Existing …
=> As a jury officer I need to be able to generate a unpaid attendance summary report (FE)

client/templates/search/index.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7409)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=456)
Previously, when a search result was limited because the APP_SETTING.SEARCH_RESULT_LIMIT_TEAM_LEADER or APP_SETTING.SEARCH_RESULT_LIMIT_BUREAU_OFFICER was set and the results set exceeded that, the user saw the results set and this message, so it was clear that the results set was limited:
{{And I see "The specified search resulted in more than 100 results. This list only shows the oldest 100." on the page}}
Now this message is not displayed to the user, and it appears that the complete results set is shown (there are >100 rows when I increase the setting)
!image-20240524-101000.png|width=1229,height=698,alt="image-20240524-101000 …
=> When search results is limited by APP_SETTING.SEARCH_RESULT_LIMIT_TEAM* setting, message isnt shown indicating that it's a limited results set

client/templates/reporting/court-reports.njk, client/templates/reporting/standard-reports/date-search/fixed-range.njk, client/templates/reporting/standard-reports/date-search/from-to.njk, server/routes/reporting/standard-report/definitions.js, server/routes/reporting/standard-report/index.js, server/routes/reporting/standard-report/standard-report.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7325)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=477)
*Acceptance Criteria*
#* Last 31 days
#* Custom date range
#** Date from (date picker) (Can’t be a date in the future)
#** Date to (date picker) (Can’t be a date in the future)
#* Back (Hyperlink)
#* *Completion of service report* (Header)
#* Print (Tab)
#* Date from
#* Date to
#* Total pool members completed
#* Report created
#* Time created
#* Court name
#* Juror number
#* First name
#* Last name
#* Completion date
```
[ ] Yes
[X] No
```
=> As a Court officer I want to generate a Completion of service report (FE)

server/routes/reporting/standard-report/standard-report.controller.js
Updated report sorting to handle blank entries better for numeric fields.
```
[ ] Yes
[x] No
```
=> hotfix/fix-report-sorting: Update report sorting

server/lib/reports/financial-audit.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7504)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=497)
Financial Audit reports date range is incorrect.
Should show smallest to largest dates that are being approve instead of smallest date to date submitted/approved.
In this example it should be Wednesday 15 May 2024 to Wednesday 15 May 2024
Instead of Wednesday 15 May 2024 to Friday 07 June 2024
!image-20240607-104221.png|width=1138,height=563,alt="image-20240607-104221.png"!
```
[ ] Yes
[X] No
```
=> Financial Audit reports date range is incorrect.

client/templates/trial-management/_partials/trial-panel.njk, client/templates/trial-management/trial-detail.njk, server/routes/trial-management/trial-management.controller.js
[JM-7154 - UAT - Jurors not visible when adding more jurors to panel after empanelment 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7154)
- removed restrictions that prevented 'Panel' members to show on list.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7154 - UAT - Jurors not visible when adding more jurors to panel after empanelment

client/templates/juror-management/attendance.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7516)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=501)
When jurors are in waiting, upon clicking the print attendance audit dropdown there should be a option for a Pool Attendance audit number which will open a report. At the moment this doesn’t occur. Attempted with both confirmed and unconfirmed attendance and still same result.
Only difference is when the attendance is confirmed the print attendance audit dropdown disappears. See screenshots.
```
[ ] Yes
[X] No
```
=> Pool Attendances Report - button to open report doesn't appear

client/templates/juror-management/attendance.njk, client/templates/juror-management/attendance/confirmed/confirmed.njk
[JM-6969 - Mark as absent doesn't work from record attendance (hidden absent table) 🔗 ](https://centralgovernmentcgi.atlassian.net/browse/JM-6969)
- Fixed wrongly hidden absent table.
```
[ ] Yes
[x] No
```
=> hotfix/JM-6969b - Mark as absent doesn't work from record attendance (hidden absent table)

server/config/validation/date-picker.js, server/config/validation/paper-reply.js, server/objects/paper-reply.js, server/routes/summons-management/update/juror-details.controller.js
[JM-7491 - Request a DOB when entering a paper summons reply 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7491)
- Making DOB not mandatory when entering paper summons reply
- Made DOB null if the string is empty
```
[ ] Yes
[x] No
```
=> hotfix/JM-7491 - Request a DOB when entering a paper summons reply

server/routes/trial-management/empanel-jury/empanel-jury.controller.js
[JM-7154 UAT - Jurors not visible when adding more jurors to panel after empanelment (show 'Panel' jurors only) 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7154)
- Filtered jurors with 'Panel' status only.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7154b - UAT - Jurors not visible when adding more jurors to panel after empanelment (show 'Panel' jurors only)

server/config/validation/pool-management.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7473)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=504)
Message is ‘Choose a pool to reassign to’
But should be ‘Choose an active pool to add selected jurors to’
!image-20240604-110914.png|width=923,height=464,alt="image-20240604-110914.png"!
```
[ ] Yes
[X] No
```
=> Error message when reassigning a juror but not selecting a pool appear to be incorrect

client/templates/administration/users/court-bureau-users.njk, client/templates/administration/users/users.njk, client/templates/custom-components/sortable-table/template.njk, client/templates/juror-management/unpaid-attendance.njk, client/templates/messaging/_partials/jurors-table.njk, client/templates/messaging/_partials/trials-table.njk, client/templates/pool-management/coroner-court/_partials/results-table.njk, client/templates/pool-management/index.njk, client/templates/pool-management/pool-overview/bureau-pool-jurors.njk, client/templates/pool-management/pool-overview/court-pool-jurors.njk, client/templates/sjo-tasks/uncomplete-service/select-jurors.njk, client/templates/trial-management/trials.njk
[JM-7295 - Pool request subheading appearing on Active Pools screen 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7295)
- Fixed hidden class for table captions.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7295 - Pool request subheading appearing on Active Pools screen

client/templates/reporting/court-reports.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7509)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=522)
* Jury not Juror
* ammendment not amendment
!image-20240607-152453.png|width=365,height=136,alt="image-20240607-152453.png"!
```
[ ] Yes
[X] No
```
=> Juror amendment incorrectly named

client/templates/juror-management/juror-record/overview.njk, server/routes/juror-management/juror-record/juror-record.controller.js, server/routes/shared/complete-service/complete-service.controller.js
[JM-7156 - When completing a juror from juror record it displays an attendance in overview until you navigate away 🔗](https://centralgovernmentcgi.atlassian.net/browse/JM-7156)
- Added the use of fetched attendances values from API call.
(to test - pull this BE branch [JM-7532](https://github.com/hmcts/juror-api/tree/JM-7532))
```
[ ] Yes
[x] No
```
=> hotfix/JM-7156 - Incorrect attendance values in overview screen

server/routes/juror-management/juror-record/juror-record.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7547
Fix missing 'enter summons' button on expenses and history tabs
```
[ ] Yes
[X] No
```
=> Bug (JM-7547) fix missing enter summons buttons

client/templates/juror-management/_partials/history-tab.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7562)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=553)
When pulling through history for a trail the history is not including the trial number or the attendance date for the trial which is should
```
[ ] Yes
[X] No
```
=> Juror history not display trial number or attendance date for trials on trial history events

client/templates/pool-management/additional-summons/index.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7599)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=557)
When we summon voters on a pool that has more jurors than required, the form will show a negative number for how many jurors is left on the required amount.
We should just probably display 0.
!image-20240619-142612.png|width=462,height=115,alt="image-20240619-142612.png"!
And this page does not have a title.
h3. Info
Having a total confirmed larger than required on the pool would cause the required number left to be negative.
!image-20240620-083206.png|width=339,height=249,alt="image-20240620-083206.png"!
```
[ ] Yes
[X] No
```
=> When summoning extra jurors "Jurors required to complete the request" shows a negative number if we summon over the required quantity

client/templates/pool-management/pool-overview/pool-history.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7180)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=563)
It shows the wrong time and message in pool history when adding a comment to a pool edit
!image-20240430-150013.png|width=451,height=276,alt="image-20240430-150013.png"!
```
[ ] Yes
[X] No
```
=> UAT - It shows the wrong time and message in pool history when editing the pool and adding a comment

server/components/filters/index.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7614
Because the FE server (probably) runs in UTC, force parsing dates from Europe/London for timezone purposes
```
[ ] Yes
[x] No
```
=> Fix (JM-7614) force parsing of dates in Europe/London

server/routes/juror-management/juror-record/juror-record.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7660
Fixes missing juror status on the history tab of the juror record
```
[ ] Yes
[x] No
```
=> Bug (JM-7660) fix missing status on history tab

client/js/export-contact-details.js, server/objects/messaging.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7669
The ajax endpoint wasn't adding juror number to the stored data if we had searched by juror number, which meant sending undefined to the server. This fixes that, and also accepts application/json from the csv endpoint as well as csv so we can actually receive error messages if this happens again.
```
[ ] Yes
[X] No
```
=> Bug (JM-7669) fix missing jurorNumber on export contact details

server/routes/summons-management/paper-reply/paper-reply.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7675
Hides the welsh language checkbox for jurors summoned to non-welsh courts 
```
[ ] Yes
[X] No
```
=> Bug (JM-7675) hide welsh checkbox for jurors summoned to non-welsh courts

server/routes/juror-management/juror-management.controller.js
Found on https://centralgovernmentcgi.atlassian.net/browse/JM-7682
Update the confirm attendance screen to get attendance by locCode of current locCode, rather than by locCode of current auth code, which meant satellites were always seeing their primary instead of local jurors.
```
[ ] Yes
[ ] No
```
=> Bug (JM-7682) fix looking up jurors by auth code instead of loccode

client/templates/juror-management/edit/deferral-available-pools.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-7707
Adds a missing hidden form field to the new available pools deferral flow
```
[ ] Yes
[X] No
```
=> Bug (JM-7707) fix missing form field in new deferal pools flow

client/templates/messaging/_common/juror-record-url.macro.njk, client/templates/messaging/_partials/jurors-table.njk, client/templates/messaging/export-contact-details/jurors-table.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7764)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=623)
the juror hyperlink is inconsistent some times it works other times it fails and says juror not found:
!image-20240713-141208.png|width=2013,height=609,alt="image-20240713-141208.png"!
```
[ ] Yes
[X] No
```
=> Messaging juror hyperlink not always working says juror not found

server/config/validation/create-trial.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7792)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=624)
Trials created before go-live weekend that are now not accessible - T20210487/0490 for Croydon. " issues;
1 - when you click on the trial is says page not found
2 - although the name was input in heritage on Friday, it is now saying that the defendant name is exceeding 16 characters
Heritage database supported up to 30 chars for trial.description
Modernised database supports 50 chars for trial.description
Backend API  supports 50 chars for Trial entity, description property
Front end is restricting to 16 chars - please update to match DB/BE
```
[ ] Yes
[X] No
```
=> Existing trials not accessible post migration

client/templates/trial-management/create-trial.njk, server/routes/trial-management/create-trial/create-trial.controller.js, server/routes/trial-management/edit-trial/edit-trial.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7797)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=628)
We should be able to see an input box that auto-completes with the court rooms.
!image-20240716-081514.png|width=821,height=206,alt="image-20240716-081514.png"!
```
[ ] Yes
[X] No
```
=> Court room dropdown autocomplete does not show for some courts

server/routes/juror-management/manage-jurors/manage-jurors.controller.js, server/routes/messaging/send-messages.controller.js, server/routes/trial-management/create-trial/create-trial.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7807)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=630)
User MODTESTCOURT has access to CARDIFF (parent court) and NEWPORT S. WALES (satellite)
1. MODTESTCOURT selects to work under court CARDIFF, creates a trial with NEWPORT S. WALES as the court
2. MODTESTCOURT selects to work under court NEWPORT S. WALES, creates a trial with NEWPORT S. WALES as the court
RESULT: both are saved to the DB with CARDIFF as the court
```
[ ] Yes
[X] No
```
=> Trials created for a satellite court are saved with parent court

client/templates/pool-management/additional-summons/index.njk, client/templates/pool-management/create-pool/summon-citizens/index.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7823)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=632)
Issue following the fix to 0 pool number issue for the bureau a new issue has occurred. Bureau now seeing a "total number of jurors in the pool has been updated since you last viewed this record”
Users have tried deleting cookies and logging back in
!image-20240717-100826.png|width=1312,height=732,alt="image-20240717-100826.png"!
```
[ ] Yes
[X] No
```
=> Bureau unable to summon jurors - FE Error

server/routes/juror-management/juror-management.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7791)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=637)
Kingston court have reported they are unable to record attendance for today (15-07-2024)
Kingston appearance count data for last few days:
|attendance_date|confirmed_count|unconfirmed_count|
|15/07/2024|1|0|
|14/07/2024|0|1|
|12/07/2024|24|0|
|11/07/2024|108|3|
SQL code:
{noformat}select		attendance_date, 
sum(case when appearance_stage = 'EXPENSE_ENTERED' then 1 else 0 end) as confirmed_count, 
sum(case when appearance_stage <> 'EXPENSE_ENTERED' then 1 else 0 end) as unconfirmed_count
from 		juror_mod.appearance a
where 		loc_code = '427'
group by	attendance_date
order by	attendance_date desc;{noformat}
Today’s confirmed record …
=> Redesign locking/unlocking confirm attendance for a day

client/templates/juror-management/_partials/heading.njk, server/routes/juror-management/juror-record/juror-record.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7757)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=646)
the processing status is summoned these need to be moved to completed for all paper responses that have moved out of summoned status.
Also occurs when a juror response is deleted (apart of the one year juror_digital housekeeping).
```
[ ] Yes
[X] No
```
=> When a juror is deferred or excuse from a paper response the green enter summons reply button still shows

server/routes/juror-management/attendance/add-attendance-date/add-attendance-date.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7872)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=651)
Thoughg I can add attendance (and conform it) via juror management-record attendance
!image-20240721-160554.png|width=1320,height=706,alt="image-20240721-160554.png"!
!image-20240721-160655.png|width=1359,height=282,alt="image-20240721-160655.png"!
```
[ ] Yes
[X] No
```
=> cannot add an attendance day via juror record for a satellite court

server/routes/juror-management/expenses/edit/edit-approval-expenses.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7888)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=657)
When user is attempting to edit expense for approval they get an error message. 
Steps to replicate (STR): Juror Number 441317934 > Expenses > Total for approval: View > Mon 01 Jul 2024 > Edit expenses for approval > Change Public transport from 8.60 to 0.00 > Recalculate totals > Save and back to all days > P. transport column showing £0.00 > Submit for approval > Error received "There is a problem. Edit at least one expense before submitting" and P. transport column resets to £8.60. Screenshots attached.
!image-20240723-105349.png|width=1187,height=852,alt="image-20240723-105349.png"! …
=> INC2529075 - Unable to edit expenses for approval [HMCTS Ref INC5632495]

server/routes/trial-management/trial-management.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7897)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=662)
If a court has more than 25 trials the user is not able to paginate through them and so cant see more than the initial 25.
```
[ ] Yes
[X] No
```
=> Trials - pagination not showing for lists larger than 25

client/templates/juror-management/attendance/unconfirmed/unconfirmed.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7916)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=664)
On record attendance screen, when a user presses the enter key to check out a juror, it is automatically defaulting to confirm all the jurors check out time rather than just an individual one
```
[ ] Yes
[X] No
```
=> Record attendance check out issue

client/templates/juror-management/juror-record/attendance.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7846)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=674)
When a juror is in panelled status we need to be able to add attendance and non attendance days via the juror record
```
[ ] Yes
[X] No
```
=> Add add attendance day and none attendance day for panel status jurors

client/templates/juror-management/_partials/attendance-tab.njk, client/templates/juror-management/_partials/history-tab.njk, server/components/filters/index.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7813)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=673)
The Juror history screen shows links to trials and attendance audits but the URL points to financial-audit. This needs updating on the FE to point to correct URL.
!image-20240716-170302.png|width=932,height=780,alt="image-20240716-170302.png"!
```
[ ] Yes
[X] No
```
=> Juror history links need updating

client/templates/response/detail.njk, server/routes/response/detail/detail.controller.js, server/routes/summons-management/process-reply/disqualify/process-reply-disqualify.controller.js, server/routes/summons-management/process-reply/reassign-before-process/reassign-before-process.controller.js, server/routes/summons-management/summons-management.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7951
From Andy
_"When processing a paper or digital reply for the Bureau, once they have completed their action the page is redirected to the “Your Work” screen. However, Juror Digital previously remained on the response details page to allow them to add any notes/log/RA’s that were needed.
As the system currently directs you back to the “Your Work” screen, its taking longer to go into the complete tab and search for the juror that they have just completed a response for. 
It would be more suitable to the business to remain in the response details page."_
```
[ ] Yes
[x] No
```
=> hotfix/JM-7951: Redirect to summons reply on processing response

server/lib/reports/financial-audit.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7923)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=684)
With a good date:
!image-20240802-095922.png|width=428,height=244,alt="image-20240802-095922.png"!
With the default date:
!image-20240802-095757.png|width=409,height=231,alt="image-20240802-095757.png"!
```
[ ] Yes
[X] No
```
=> Payment audit report - everyone still showing 1st January 2000 as the submitted date

server/routes/pool-management/deferral-maintenance/deferral-maintenance.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7986)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=692)
```
[ ] Yes
[X] No
```
=> Deferral Maintenance uses owner instead of locCode when returning deferred jurors

server/routes/juror-management/attendance/attendance.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7900)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=%pullRequestNumber%)
It is correct (my checkout time is earlier than my checkin time), but the error is displayed incorrectly
!image-20240724-100921.png|width=773,height=166,alt="image-20240724-100921.png"!
```
[ ] Yes
[X] No
```
=> Error message is displayed wrong when checkout time < check in time

Dockerfile, server/app.js, server/lib/appinsights.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7829
Alter pod startup to allow Node to receive the SIGTERM direct rather than via yarn. This allows Node to then wait before closing connections (which allows any traffic to be returned to client).
```
[ ] Yes
[x] No
```
=> changes to catch termination

client/templates/juror-management/_partials/attendance-tab.njk, client/templates/juror-management/expense-record/_partials/approval-table.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7990)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=697)
We have updated the reports to show a blank field but left some tables out.
```
[ ] Yes
[X] No
```
=> Update expenses tables to not show the default date set (2000-01-01)

server/components/filters/index.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7973)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=682)
we expected all trial numbers to start with {{T}}… obviously this is not correct
!image-20240801-114950.png|width=1618,height=1634,alt="image-20240801-114950.png"!
```
[ ] Yes
[X] No
```
=> Trial links not rendering properly on juror-history

client/templates/reporting/standard-reports/date-search/fixed-range.njk, server/config/validation/report-search-by.js, server/routes/reporting/standard-report/standard-report.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7997)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=700)
It does not crash on all of them, but I have identified some reports that do not have correct validation in place.
* {{unconfirmedAttendance}}
* all jury-expenditure levels
```
[ ] Yes
[X] No
```
=> Application crashes on trying to search for reports that need a date-range

server/objects/expenses.js, server/routes/juror-management/approve-expenses/approve-expenses.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7999)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=701)
We are seeing a number of fails with an {{ECONNRESET}} error on some api calls.
These seem to only happen on calls that use the {{request-promise}} (http requests helper) package and so we thought it would be good to update to the more up-to-date {{axios}} package (also used in the application) to see if the issue still happens.
```
[ ] Yes
[X] No
```
=> Replace request-promise with axios on get expenses for approval and approving expenses

server/components/filters/index.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8038)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=713)
When trying to find out which trial a juror was in the Trial number is not showing up on History.
example juror 344506279 - only the first three number 34S are showing - the trial number should be 43SP0054123
This is happening with multiple jurors not just the above.
```
[ ] Yes
[X] No
```
=> INC2554492 - Trial numbers incomplete or missing on Juror history

server/routes/documents/letters-list/letters-list.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8055)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=721)
INC2536487 - When reprinting reminders, the user get a error message - unable to reprint for selected jurors [HMCTS Ref INC5634218]
When reprinting reminders, the user get a error message - “Unable to reprint letters for the selected jurors”.
It is happening when trying to select all Juror records in a pool (451240901) and then send out a reminder letter. 
Error in the log:
{"timestamp":"2024-07-30 10:40:01","message":"*eq(null) is not allowed. Use isNull() instead*"}
```
[ ] Yes
[X] No
```
=> INC2536487 - When reprinting reminders, the user get a error message - unable to reprint for selected jurors [HMCTS Ref INC5634218]

client/templates/juror-management/_partials/heading.njk, client/templates/juror-management/juror-record/attendance.njk, client/templates/juror-management/juror-record/overview.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8068)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=732)
I have deferred a juror to June next year, however, the next due at court still showing Monday next week. He still showing up on my attendance list for Monday. (SCREENSHOTS IN TEAMS CHAT) I have manually changed the 'next due at court date' but this still need fixing
Hide the "next due at court date" for deferred jurors to avoid confusion with this date. Ticket needed.
```
[ ] Yes
[X] No
```
=> Hide the "next due at court date" for deferred jurors to aviod confusion with this date. 

client/templates/juror-management/attendance.njk, client/templates/trial-management/returns/return-attendance.njk, server/routes/juror-management/juror-management.controller.js, server/routes/trial-management/returns.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7967)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=733)
Steps to replicate:
* some jurors are on a trial for the day
* some jurors are in waiting for the day
* confirm attendance for one or more checked in jurors in waiting
* return the jury without setting a check out time
as a result, the jurors returned from the trial will not be visible/available to add expenses
N.B. setting the appearance_confirmed flag for the returned jurors would not resolve the issue
agreed fix for this is the following:
* Display a message when a previous day has not been confirmed to prompt users to confirm that day before checking jurors in and empanelling them as this will drop them off yesterday list as …
=> Returning a jury without check out time can leave jurors in limbo

client/templates/pool-management/additional-summons/index.njk, client/templates/pool-management/create-pool/summon-citizens/index.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8093)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=742)
Bureau unable to summon additional jurors to pools. "Something has changed since last viewed" error message is appearing.
15/8 ASB/BE held call with the Bureau - Looks like its because the total summoned count on the screen did not match to the number of juror_pools assigned to that pool It could be down to court owned records or inactive pools
```
[ ] Yes
[X] No
```
=> Bureau unable to summon additional jurors to pools. "Something has changed since last viewed" error message is appearing.

client/templates/administration/users/user-record.njk, server/routes/administration/users/edit-user/edit-user.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-8082
Updated edit user permission in template to check for manager role or system admin. 
Aligning with the types of users that can edit user details.
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
User Type | Can edit user?
-- | --
Administrator | Yes
Court User Standard | No
Court Manager | Yes
Court SJO | No
Court Manager & SJO | Yes
Bureau User Standard | No
Bureau Manager | Yes
</body>
</html>
```
[ ] Yes
[x] No
```
=> hotfix/JM-8082: Edit user button not showing in "Court Administration" section of the application

client/templates/summons-management/paper-reply/edit-address.njk, client/templates/summons-management/paper-reply/edit-name.njk, server/routes/juror-management/edit/juror-edit.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8096)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=746)
When editing juror details on the summons reply or edit juror details screen we get three options.
Fix error in current name, Enter a new name, and change address these three options take you to a pop-out screen which allows you to edit the values.
This pop-out screen current uses the word save to commit the changes however this needs to be updated to “Review Edit” to avoid confusion as this action does not commit the change to the database but rather takes you to a review screen
!image-20240820-140329.png|width=1606,height=387,alt="image-20240820-140329.png"!
!image-20240820-140345.png|width=930,height=738,alt="image-20240820-140 …
=> Rename Juror Details pop-out save buttons to be "Review Edit"

client/templates/juror-management/_partials/third-party-details.njk, client/templates/response/_partials/juror-details.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8053)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=745)
When updating the third party details from the juror record the option is there but it will not save the changes even when save is selected in the application.
[~accountid:62306f3e50cceb0070797d12]  a design change is required to this section to allow the user to select how the juror should be contacted i.e contact via third party or contact via juror details.
We will need to update the edit juror details API to support the third party details section.
Add a new table for juror_third_party
Update the get juror details API to include third party details
Update the FE to send / load in this new data
Update digital and paper …
=> Third party details in the juror record does not save the details

client/templates/summons-management/_common/details-banner-new.njk
https://centralgovernmentcgi.atlassian.net/browse/JM-8098
Updated summons reply warning sign to only show for refused excusal.
2nd deferral refusal warning should only show on juror record (which it currently does)
```
[ ] Yes
[x] No
```
=> hotfix/JM-8098:  Flag marked showing incorrectly on straight through responses and reasonable adjustment responses.

server/routes/response/detail/detail.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8101)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=749)
Warning icon missing from records that should display
Ref (JM-8039) is also not fully fixed. I spoke to Ben about it before he joined your call but we only had a few minutes. You might need to check in with Ben on that but the flag is incorrectly applying to the wrong responses. (It is working on the ones it should as well) its just that additional incorrect bit we need to fix. 
h3. Icon display:
|| ||*Deferral refused*||*Excusal refused*||
|Summons digital|No|Yes|
|Summons paper|No|Yes|
|Juror record|Yes|Yes|
```
[ ] Yes
[X] No
```
=> Warning icon missing from records that should display

client/templates/reporting/persons-attending/attendance-date.njk, server/routes/reporting/persons-attending/persons-attending-controller.js, server/routes/reporting/standard-report/definitions.js, server/routes/reporting/standard-report/standard-report.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8135)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=764)
Currently we include all jurors with a status responded panel and juror by default if they have the right next attendance date. Going forward we need to add a check box (as per the include summoned status) to include panel or juror status jurors and the default is of only responded jurors with the correct next attendance date:
!image-20240823-150358.png|width=1664,height=700,alt="image-20240823-150358.png"!
```
[ ] Yes
[X] No
```
=> The persons attending details and summery to add an option to include panel/juror status jurors

server/lib/back-link.js
https://centralgovernmentcgi.atlassian.net/browse/JM-8111
Updated dynamic back link bypass urls to also accept RegExp.
Added juror management edit details flow to bypass urls to avoid data issues.
```
[ ] Yes
[x] No
```
=> hotfix/JM-8111: Internal server error when clicking Back link after age disqualification

client/templates/juror-management/_partials/attendance-tab.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8138)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=768)
As per title. ordering is incorrect. I thought it might be ordering on date entered, but on looking in the DB I dont think that’s it either.
!image-20240827-110514.png|width=1457,height=412,alt="image-20240827-110514.png"!
!image-20240827-110638.png|width=1566,height=223,alt="image-20240827-110638.png"!
```
[ ] Yes
[X] No
```
=> Attendance ordering incorrect on juror history

client/templates/juror-management/dismiss-jurors/jurors-table.njk, server/routes/juror-management/dismiss-jurors/dismiss-jurors.controller.js
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8125)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=761)
Due to this being a very volatile list, that would change on every api call, we opted for serving the whole list then having node doing the work on pagination and sorting… this needs to be updated to sort the whole available list and not just the current page.
```
[ ] Yes
[X] No
```
=> Sorting on dismiss-jurors list sorts only the current page

server/routes/response/detail/detail.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7949
Removed circular call to an endpoint that no longer exists, when  juror_pool has certain statuses and the response is in TODO. 
In Juror Mod if the juror record is updated to certain statuses prior to summons being processed, the response is closed. This was not the case before and another endpoint was called to close the response, which is no longer in use, causing circular call and crashing app.
```
[ ] Yes
[x] No
```
=> hotfix/JM-7949: A juror with a juror_pool status of 2 and response in TODO tries to call a removed endpoint

server/routes/juror-management/juror-management.controller.js
https://centralgovernmentcgi.atlassian.net/browse/JM-8169
Variable that was used to show previous day link was calculated wrong. It was using the current date as the base, meaning that links for previous months would have the correct day number, but still be using the current month,
Updated to calculate yesterday's date correctly.
```
[ ] Yes
[x] No
```
=> hotfix/JM-8169: INC2576126 - Courts unable to confirm attendance for Friday 30th August

client/templates/juror-management/juror-record/_partials/attendance-table.njk
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8147)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=772)
When visiting a {{juror-record/attendance}} page, there will be a table of attendances that the juror has, this has a time-in / out columns and these should always be populated… an attendance will never be confirmed without a time-in / out… it happens that some entries in the database do not have a time-out and this is causing the view to fail on rendering the html. 
```
[ ] Yes
[X] No
```
=> INC2571749 - Juror-record attendance breaks when a time-out is not set

server/config/validation/additional-summons.js, server/objects/axios-instance.js, server/routes/pool-management/additional-summons/additional-summons.controller.js, server/routes/pool-management/create-pool/summon-citizens/summon-citizens.controller.js
[JS-118](https://tools.hmcts.net/jira/browse/JS-118)
Updated axios error handler to pass through error reasonCode if it is present.
Updated invalid yield message to 'The number of citizens summoned is too high and exceeds the yield'.
```
[ ] Yes
[x] No
```
=> Hotfix/JS-118: Invalid yield message not showing

server/routes/pool-management/coroner-court/coroner-court.controller.js
https://tools.hmcts.net/jira/browse/JS-129
Update so that coroner pool creation does not fail if there are no entries in the voters table.
```
[ ] Yes
[x] No
```
=> hotfix/JS-129: Coroner's pool fails if no voters available

client/templates/trial-management/returns/return-attendance.njk, server/routes/trial-management/returns.controller.js
[JS-160](https://tools.hmcts.net/jira/browse/JS-160)
Reinstate option to 'Return but do not confirm attendance' when returning jurors from a trial.
```
[ ] Yes
[x] No
```
=> task/JS-160: Reinstate Middle Option for Returning Jurors

client/templates/pool-management/summoning-progress/index.njk
[JS-232](https://tools.hmcts.net/jira/browse/JS-232)
Default to 'Crown Court' radio button when performing summoning progress search
```
[ ] Yes
[x] No
```
=> task/JS-232: Default summoning progress search to crown court

client/templates/juror-management/edit/juror-edit-details.njk, client/templates/juror-management/juror-record/details.njk
[JS-352](https://tools.hmcts.net/jira/browse/JS-352)
Hide welsh language juror details selection for non-welsh courts
```
[ ] Yes
[x] No
```
=> Task/JS-352: Hide welsh language juror details for non-welsh courts

client/templates/documents/_common/letters-list.njk
https://tools.hmcts.net/jira/browse/JS-422
Fix delete pending letter success message not showing.
```
[ ] Yes
[x] No
```
=> hotfix/JS-422: Fix delete letter banner message not displaying

server/routes/juror-management/reassign/reassign.controller.js
[JS-450](https://tools.hmcts.net/jira/browse/JS-450)
Fixed the following crash causing bug.
Reassign juror from pool overview -> select jurors who don’t meet criteria to be moved (i.e. deferred status) -> shows screen to continue with rest of the available jurors -> if left with 0 jurors allowed to move/reassign -> FE app crashes
```
[ ] Yes
[x] No
```
=> hotfix/JS-450: Fix reassign jurors crash
